redhat-developer/lsp4ij

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/operations/AbstractLSPInlayProvider.java, src/main/java/com/redhat/devtools/lsp4ij/operations/codelens/LSPCodelensInlayProvider.java, src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/operations/documentLink/LSPDocumentLinkAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/operations/documentLink/LSPDocumentLinkGotoDeclarationHandler.java, src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProvider.java, src/main/java/com/redhat/devtools/lsp4ij/operations/highlight/LSPHighlightUsagesHandlerFactory.java, src/main/java/com/redhat/devtools/lsp4ij/operations/inlayhint/LSPInlayHintInlayProvider.java, src/main/java/com/redhat/devtools/lsp4ij/operations/navigation/LSPGotoDeclarationHandler.java, src/main/resources/META-INF/plugin.xml
refactor: Associate validation, completion, etc with any language
Fixes #26
=> refactor: Associate validation, completion, etc with any language

build.gradle.kts, src/main/resources/META-INF/plugin.xml
=> build: update dependencies and description

src/main/java/com/redhat/devtools/lsp4ij/commands/LSPCommandAction.java
feat: provide a base class for LSP command action
See usage in IJ Quarkus with https://github.com/redhat-developer/intellij-quarkus/pull/1285
=> feat: provide a base class for LSP command action

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerFactory.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/ServerExtensionPointBean.java, src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/resources/META-INF/plugin.xml
feat: use server factory
This PR provides a new API LanguageServerFactory which takes care of to create StreamConnectionProvider, LanguageClientImpl instances and LanguageServer class (server interface). 
It means that there is now just one an attribute (factoryClass) which is used to declare server instead of 3 attributes (class, clientImpl, serverInterface), because it seems that IJ extension point can manage only one attribute to instanciate otherwise you need to use internal API to instanciate class.
This PR avoids to use internal API and it simplifies the code (no need to manage some scope project / application), because the instance are managed with Java.
See changes https://github.com/redhat-developer/intellij-quarkus/pull/1289/files#diff-6bfdea29cf5a3281628af3c42227a28ac4c8041a3d11 …
=> feat: use server factory

README.md, src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/operations/AbstractLSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/operations/LSPInlayHintProvidersFactory.java, src/main/java/com/redhat/devtools/lsp4ij/operations/codelens/LSPCodelensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/operations/inlayhint/LSPInlayHintsProvider.java, src/main/resources/META-INF/plugin.xml
feat: Use inlayhint factory to avoid declaring LSP codelens/inlayhint support in an external plugin
This PR also fixes https://github.com/redhat-developer/lsp4ij/issues/10
=> feat: Use inlayhint factory to avoid declaring LSP codelens/inlayhint support in an external plugin

build.gradle.kts, gradle.properties, src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProvider.java, src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/MarkdownConverter.java, src/test/java/com/redhat/devtools/lsp4ij/operations/documentation/MarkdownConverterTest.java
Before:
After:
Also fixes #58 
=> fix: properly render markdown tables

src/main/java/com/redhat/devtools/lsp4ij/operations/codeactions/LSPLazyCodeActionIntentionAction.java
When  codecation returns a command (left part), there is an NPE. I discover this use case with CSS whit:
```
a {
colo: red;
}
```
The CSS LS provides a command which fixes colo into a known property.
=> fix: NPE when codeaction is a command

docs/DeveloperGuide.md, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java, src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowPanel.java, src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleView.java, src/main/java/com/redhat/devtools/lsp4ij/console/LSPTextConsoleBuilderImpl.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerTreeNode.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/ContentTypeToLanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/ServerLanguageMapping.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/ServerMapping.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/ExtensionLanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/LanguageMappingExtensionPointBean.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/ServerExtensionPointBean.java, src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerConfigurable.java, src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerListConfigurable.java, src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerView.java, src/main/resources/META-INF/plugin.xml
As LanguageServerRegistry is very hard to read because it is a big class, this PR move inner class server definion, mapping, etc from LanguageServerRegistry to a proper package server.definition.
It provides too a new attribute languageId to use it when TextDocument is opened.
=> refactor: move classes to definition package.

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/internal/SupportedFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/operations/color/ColorInlayPresentation.java, src/main/java/com/redhat/devtools/lsp4ij/operations/color/LSPColorProvider.java
This PR initialize textDocument/color support by showing as colorized square (like vscode, Eclipse LSP4E does). 
This support should be improved by giving the capability to click on the square to open a color dialog to choose the color and update the editor. We could improve that in an another PR.
Here a screenshot with the CSS language server from vscode:
=> feat: initialize textDocument/color support

src/main/java/com/redhat/devtools/lsp4ij/operations/diagnostics/SeverityMapping.java
When the language server does not set the severity for a diagnostic we choose a default of Information. On IntelliJ this means no on-screen highlighting. It would be better to be like VS Code and use a red underline (Error) by default.
=> fix: Change default highlight severity from Info to Error.

src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionProposal.java
=> fix: display proper completion documentation

src/main/java/com/redhat/devtools/lsp4ij/operations/completion/CompletionItemComparator.java, src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionContributor.java, src/test/java/com/redhat/devtools/lsp4ij/operations/completion/CompletionItemComparatorTest.java
Fixes #69 
Same sort as VS Code appears to be used now:
vs
=> fix: sort completion items by sortText

src/main/java/com/redhat/devtools/lsp4ij/operations/completion/SnippetTemplateLoader.java, src/main/java/com/redhat/devtools/lsp4ij/operations/completion/snippet/LspSnippetParser.java, src/test/java/com/redhat/devtools/lsp4ij/operations/completion/snippet/PlaceholderTest.java
fix: Apply completion with placeholder which have no name ${1:}is bugged
Fixes #82
Here a demo which fixes Go  completion:
=> fix: Apply completion with placeholder which have no name ${1:}is bugged

src/main/java/com/redhat/devtools/lsp4ij/internal/SupportedFeatures.java
By playing with https://github.com/typescript-language-server/typescript-language-server the JavaScript/TypeScript files don't report publishDiagnostics because the language server check the publishDiagnostics https://github.com/typescript-language-server/typescript-language-server/blob/a00c1cc364b3bcdbab0cf2ac3d5b6e6adc4d9377/src/lsp-server.ts#L131
LSP4IJ client should set the proper publish diagnostic capability.
=> fix: Support publishDiagnostics as capability

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/resources/templates/node/typescript-language-server.md
Given this JavaScript / TypeScript file:
```
const a = "";
a.charA
```
The typescript-language-server provides two code actions:
which doesn't work.
When you apply this code action, it doesn't nothing with an error, because the code action execute `workspace/applyEdit` which tries to update the document but in not in write action thread. The excution of the document update must be done in write action mode.
This code action must create a new file, the apply edit must create the file if it doesn't exist.
This PR fixes those é problems.
=> fix: workspace/applyEdit must be executed in write action

src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionProposal.java
fix: "IllegalArgumentException: Invalid range specified" thrown on  completion with the typescript language server
Fixes #91
The PR fixes the issue and apply completion should work correctly:
=> fix: "IllegalArgumentException: Invalid range specified" thrown on completion with the typescript language server

src/main/java/com/redhat/devtools/lsp4ij/internal/SupportedFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java
This PR defines a tooltip for annotation to show source + code of the LSP diagnostic. When code has a code description which defines an href (ex : go ls), it display the code as hyperlink:
Here a screenshot with typescript ls (it doesn't support href for code)
=> feat: display source + code of LSP diagnostic as tooltip

src/main/java/com/redhat/devtools/lsp4ij/internal/PromiseToCompletableFuture.java
fix: check if coalesceBy is not a an array of null Object
Fixes: #104
=> fix: check if coalesceBy is not a an array of null Object

src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionProposal.java, src/main/java/com/redhat/devtools/lsp4ij/operations/completion/snippet/LspSnippetParser.java, src/test/java/com/redhat/devtools/lsp4ij/operations/completion/snippet/PlaceholderTest.java
fix: escape \$ for snippet completion
This PR takes care of `\$` which escape the `$` to add it as text. Here a demo with `@for` in scss file:
Before the PR:
After the PR:
=> fix: escape \$ for snippet completion

docs/LSPSupport.md, src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/internal/SimpleLanguageUtils.java, src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProvider.java, src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPTextHoverForFile.java
fix: LSP Hover support doesn't work without Psi
Fixes #97
This PR activate the LSP hover when file is associated with TextMate. Here a screenshot with JDT LS
There is a problem with the popup position which could hide the hovered element:
=> fix: LSP Hover support doesn't work without Psi

build.gradle.kts
This PR provides the capability to download the IJ sources which is very nice to debug it.
In my case, I spend my time to debug IJ:
* to understand how to implement features (ex : signature help, etc)
* understand why we have some new bugs with EAP versions since IJ breaks the behavior fo some features (like inlay hints).
=> build: download IJ sources to debug it

src/main/java/com/redhat/devtools/lsp4ij/console/actions/AutoFoldingAction.java
fix: com.intellij.diagnostic.PluginException: ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon.
Fixes #131
=> fix: com.intellij.diagnostic.PluginException: ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon.

src/main/java/com/redhat/devtools/lsp4ij/operations/LSPPsiElement.java, src/main/java/com/redhat/devtools/lsp4ij/operations/LSPPsiElementFactory.java, src/main/java/com/redhat/devtools/lsp4ij/operations/navigation/LSPGotoDeclarationHandler.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsagePsiElement.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsagesManager.java
fix: jump to proper location when no Psi element
This PR fixes the position but not the underlined.
=> fix: jump to proper location when no Psi element

src/main/java/com/redhat/devtools/lsp4ij/operations/codeactions/LSPLazyCodeActions.java
fix: Quick fixes are not reliably made available to the user the first time they hover over a diagnostic.
Fixes #138
This PR wait until that code actions are loaded to show the hover instead of waiting for 25ms (in master) only.
The wait is stopped when progress is cancelled (ex : user move the mouse).
@mrglavas could you try this PR please and tell us if it fixes your issue.
=> fix: Quick fixes are not reliably made available to the user the first time they hover over a diagnostic.

src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java
perf: dont send empty didChange notification
To reproduce the problem, select a code block, press on TAB, you should see several didChange which are empty (tested with TypeScript LS)
=> perf: dont send empty didChange notification

src/main/java/com/redhat/devtools/lsp4ij/LSPFileSupport.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java, src/main/java/com/redhat/devtools/lsp4ij/operations/foldingRange/LSPFoldingRangeBuilder.java, src/main/java/com/redhat/devtools/lsp4ij/operations/highlight/LSPHighlightSupport.java, src/main/java/com/redhat/devtools/lsp4ij/operations/highlight/LSPHighlightUsagesHandler.java, src/main/java/com/redhat/devtools/lsp4ij/operations/highlight/LSPHighlightUsagesHandlerFactory.java
fix: NPE when LSP DocumentHighlightKind is null
This PR:
* Fixes #160
* Use an LSP highlight support (to be standard with other features like foldingRange, etc) and provide teh capability to cancel the LSP requests highlight when file is closed
* Improve folding ranges to avoid using Timeout
=> fix: NPE when LSP DocumentHighlightKind is null

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageTargetProvider.java
Something fishy with intermediate diagnostics being computed on stale lines
Fixes #125
=> fix: compute range from 1st non-whitespace word, if start==end

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/AbstractLSPFormattingService.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingParams.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingSupport.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_toOffsetTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/TypeScriptCompletionTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/formatting/ClojureFormattingTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/formatting/TypeScriptFormattingTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPFormattingFixtureTestCase.java
fix: Formatting fails when position end is out of range of the document
Fixes #183
=> fix: Formatting fails when position end is out of range of the document

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/ClojureCompletionTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCompletionFixtureTestCase.java
This PR fixes #181
and have a test
=> fix: Wrong generated content after an LSP completion apply without TextEdit

docs/LSPSupport.md, src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java, src/main/java/com/redhat/devtools/lsp4ij/LSPNotificationConstants.java, src/main/java/com/redhat/devtools/lsp4ij/LSPRequestConstants.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPFeatureSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/codelens/LSPCodeLensSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPHoverSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/filewatchers/FileSystemWatcherManager.java, src/main/java/com/redhat/devtools/lsp4ij/features/filewatchers/PathPatternMatcher.java, src/main/java/com/redhat/devtools/lsp4ij/features/foldingRange/LSPFoldingRangeSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/signatureHelp/LSPSignatureHelpSupport.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSupport.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageTargetProvider.java, src/test/java/com/redhat/devtools/lsp4ij/features/filewatchers/FileSystemWatcherManagerTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/filewatchers/PathPatternMatcherTest.java
feat: Support pattern from FileSystemWatcher
Fixes #11
This PR support now pattern and I have integrated the same test than vscode. However there is some limitations:
* using `**/` (managed with Java NIO glob) is not optional. So if you have the following pattern `C:/foo/**/*.ts`, the `C:/foo/bar.ts` is not valid altough it is valid in vscode. Since I have seen a lot of usecases about that, I implemented this support **It is now supported.**
* using `*`, same thing it is not optional. No see usecases for that.
I have written tests for glob pattern but not for the implementation of workspace/didChangeWatchedFiles when a file is created, deleted, moved. It should be nice to write those test in a separate PR.
=> feat: Support pattern from FileSystemWatcher

src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowPanel.java, src/main/java/com/redhat/devtools/lsp4ij/console/actions/ApplyLanguageServerSettingsAction.java, src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerView.java, src/main/java/com/redhat/devtools/lsp4ij/settings/UserDefinedLanguageServerSettings.java, src/main/resources/messages/LanguageServerBundle.properties
Here a demo:
To make the save button more clear to use, create a balloon when updating the settings pointing to the save button/icon. The balloon is shown once every time the settings are changed from an unmodified state.
I'm wondering if the naming/component fetching can be done better
- the applyComponent is still fetched using the index
- not sure if adding the ACTION_TOOLBAR_COMPONENT_NAME to ApplyLanguageServerSettingsAction is the cleanest option, but I think it is better than using `getComponent(n)`
Currently missing from this PR is the possibility to have the balloon not show up any more
=> feat: Promote save settings when updating LSP settings

src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowPanel.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java
fix: Details pane in consoles view is not removed after deleting the last LS
Fixes #220
=> fix: Details pane in consoles view is not removed after deleting the last LS

src/main/java/com/redhat/devtools/lsp4ij/LSPFileSupport.java, src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/LSPRequestConstants.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/CompletionData.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/CompletionPrefix.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionParams.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionSupport.java, src/main/java/com/redhat/devtools/lsp4ij/internal/SupportedFeatures.java
fix: Infinite completionItem/resolve when documentation for completion returns nothing
Fixes #182
This PR:
* uses now LSPCompletionSupport pattern to cancel  the future when file is closed and cache the value if offset has not changed
* fix the infinite loop
* resolve 'detail' and 'additionaltextEdits'.
For resolving 'detail', you can see that in action with TypeScript LS:
The only annoying thing is that `completionItem/resolve` is called for all completion items. It should be called just for the selected completion item but I don't know how to do that in IJ.
It seems performance are good with TypeScript LS, we can keep that and improve it in the future if we see some performance problems. vscode does that, it display detail only for the selected item:
=> fix: Infinite completionItem/resolve when documentation for completion returns nothing

src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPPrepareRenameSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameRefactoringDialog.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameSupport.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java, src/main/resources/messages/LanguageServerBundle.properties
feat: When rename does nothing, notify it with a message
Fixes #217
This PR show errors when 
* language server is starting, as we wait for 200ms to get the rename capability, there is a TimeOutException which is thrown (the server is not ready). In this case we display the hint error:
* prepare rename fails (ex: Clojure LS) 
* or after a rename process done with a dialog
In this case:
* when language server throws an error when rename is consumes, the error is not display as hint (try to rename import with go ls), you can see no identifier found as error which comes from the go ls:
another error with go ls:
* when language server returns an empty workspaceedit instead of throwing error, there is thisgeneric message (ex : with TypeScript LS):
=> feat: When rename does nothing, notify it with a message

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_getTokenRangeTest.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_toPositionTest.java, src/test/java/com/redhat/devtools/lsp4ij/TextAndOffset.java
This PR simplify the LSPIJUtils#toPosition by avoiding computing a text range and add tests.
=> test: Add tests for LSPIJUtils#toPosition

src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameRefactoringDialog.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java, src/main/resources/messages/LanguageServerBundle.properties
fix: don't process prepare rename / rename in EDT to avoid freezing IJ
=> fix: don't process prepare rename / rename in EDT to avoid freezing IJ

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/server/ProcessStreamConnectionProvider.java, src/main/resources/templates/template-ls.json
When running user defined LS, if the IDE has not been started from a terminal, the proper environment variables are missing, leading to programs usually found in PATH to be missing.
The patch injects them into the ProcessBuilder of the LS command.
=> fix: inject env variables to LS process builder, run in shell

docs/LSPSupport.md, src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/ServerMessageHandler.java, src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/java/com/redhat/devtools/lsp4ij/internal/SupportedFeatures.java
feat: Support for window/showDocument
Fixes #237
You can test this PR with Clojure LSP with `Create Test` code action:
This code action generate the test file and after that `window/showDocument` is called to open the generated file:
=> feat: Support for window/showDocument

src/main/java/com/redhat/devtools/lsp4ij/AbstractDocumentMatcher.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java
The Quarkus URL codelens are never shown since it delegate the computation of CodeLens in a new Thread which visits the AST to return the position /url of the codelens.
Java file in Quarkus project uses a document matcher and in the codelens context, it is not in read action mode, it is executed in async mode but for a reason that I cannot explain it cancels the matcher which cancels the codelens future.
The fix is to resolve document matcher synchronously and don't cancel the codelens future when a ProgressCancelledException is thrown.
=> fix: Quarkus codeLens url are never shown

src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPFeatureSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/intention/LSPIntentionCodeActionSupport.java
fix: Prevent from NPE when LSP code action request future is invalid
Fixes #252
Fixes #251
=> fix: Prevent from NPE when LSP code action request future is invalid

src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkGotoDeclarationHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/foldingRange/LSPFoldingRangeBuilder.java, src/main/java/com/redhat/devtools/lsp4ij/features/foldingRange/LSPFoldingRangeSupport.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPFormattingFixtureTestCase.java
fix: Ensure didOpen is called before other features than documentLink, codelens, etc
Fixes #173
This PR should fix the original issue. The main idea is when we try to connect a file to a language server we return the didOpenFuture and each LSP features futures wait for this didOpenFuture.
But it is not enough since didOpen is a notification and could take some times, we wait for 500ms after the didOpen notification is sent.
It seems it is working, the only problem that I have seen is when your start IJ there are some compute of indexes, ls wait for dumb is finished to start it and sometimes teh codelens are not displayed when editor was opened when IJ starts.
When IJ is started and you stop ls and you retry it, codelens are displayed correctly.
=> fix: Ensure didOpen is called before other features than documentLink, codelens, etc

src/main/java/com/redhat/devtools/lsp4ij/client/ExecutionAttemptLimitReachedException.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java, src/main/java/com/redhat/devtools/lsp4ij/internal/PromiseToCompletableFuture.java, src/main/java/com/redhat/devtools/lsp4ij/internal/ResponseErrorExceptionWrapper.java
fix: avoid logging error from LSP4J when LSP response send an error.
When PsiJavaFile is not ready it can throw a PrgressCancelException, see explanation at https://github.com/redhat-developer/lsp4ij/pull/267
We try 5 times to collect information from Java components (visit PsiJavaFile , use search) for some LSP features which requires Java like IJ Quarkus and after that ExecutionAttemptLimitReachedException is thrown.
This error is logged by LSP4J https://github.com/eclipse-lsp4j/lsp4j/blob/d0757511e66be409ea9c27440e426616e53339e3/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/RemoteEndpoint.java#L62 which is very annoying because IJ logs that.
To avoid this log, the promise to completable future must throw exception which extends LSP4J ResponseErrorException.
This PR …
=> fix: avoid logging error from LSP4J when LSP response send an error.

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkGotoDeclarationHandler.java
=> fix: prevent IJ from reporting an error in LSPIJUtils.getPsiFile if the file has been deleted

src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPPrepareRenameSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameRefactoringDialog.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameUnitTestMode.java, src/main/resources/messages/LanguageServerBundle.properties, src/test/java/com/redhat/devtools/lsp4ij/features/rename/GoRenameTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/rename/QuteRenameTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/rename/RustRenameTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPFormattingFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPRenameFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockLanguageServer.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockTextDocumentService.java
test: Add tests for rename
Fixes #253
This PR adds all tests for prepare rename / rename support with all usecases
* when language server don't support prepare rename (see QuteRenameTest)
* when language server supports prepare rename with only Range (see RustRenameTest)
* when language server supports prepare rename with PrepareRenameResult (see GoRenameTest)
* when language server supports prepare rename with PrepareRenameResult default behavior (see GoRenameTest)
* when prepare rename throws an error when renamed cannot happen(see RustRenameTest)
* when rename throws an error  (see GoRenameTest)
* fixes the case when prepare rename returns null (see GoRenameTest), in this case the rename cannot happen (according to the LSP spec).
=> test: Add tests for rename

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/internal/ClientCapabilitiesFactory.java
refactor: move SupportedFeatures into ClientCapabilitiesFactory
=> refactor: move SupportedFeatures into ClientCapabilitiesFactory

src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPRenameFixtureTestCase.java
trial n error approach to fix LSPRenameFixtureTestCase tests occasionally failing on GHA mac
=> chore: tweak mock server sleep time for LSPRenameFixtureTestCase

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
fix: Language server console is always showing timer with "stopping pid" message, even if the file is open.
Fixes #302
=> fix: Language server console is always showing timer with "stopping pid" message, even if the file is open.

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingSupport.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/BootstrapPropertiesCompletionTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/ClojureCompletionTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/GoCompletionTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/MicroProfileConfigPropertiesCompletionTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/QuteCompletionTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/TypeScriptCompletionTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCompletionFixtureTestCase.java
fix: Completion additionalTextEdits generates wrong content
Fixes #300
=> fix: Completion additionalTextEdits generates wrong content

src/main/java/com/redhat/devtools/lsp4ij/JSONUtils.java
Since IJ 2024.2 the `PluginAwareClassLoader#tryLoadingClass` is marked as internal API https://github.com/JetBrains/intellij-community/blob/9623948a62511ddfac263b89799c924ebd24d6d2/platform/extensions/src/com/intellij/ide/plugins/cl/PluginAwareClassLoader.java#L42
Jetbrains forbids the release of LSP4IJ to accept the 2024.2 version.
This PR removes the use of `PluginAwareClassLoader#tryLoadingClass`
=> fix: don't use PluginAwareClassLoader#tryLoadingClass

src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java, src/main/resources/templates/rust-analyzer/initializationOptions.json
Given this Rust file:
```
fn main() {
Arc|
}
```
When completion is applied for Arc in vscode it generates the import like this:
```
use std::sync::Arc;
fn main() {
Arc
}
```
In IJ it doesn't generate the `use std::sync::Arc;` because in LSP4IJ we don't resolve additionalTextEdits if it is empty and Rust return empty additionalTextEdits .
This PR fixes the problem:
=> fix: resolve additionalTextEdits if empty

src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java, src/main/java/com/redhat/devtools/lsp4ij/internal/ClientCapabilitiesFactory.java
feat: Support for labelDetails completionItem
Given this rust file:
```
fn main() {
CharArr|
}
```
You should see the completion wich render labelDetails#detail as completion tail text:
I tried to have the same render than vscode:
Here LSP traces:
```
[Trace - 17:18:10] Received response 'textDocument/completion - (227)' in 13ms.
Result: {
"isIncomplete": true,
"items": [
{
"label": "CharArraySearcher",
"labelDetails": {
"detail": " (use std::str::pattern::CharArraySearcher)",
"description": "CharArraySearcher\u003c\u0027_, _\u003e"
},
"kind": 22,
"detail": "CharArraySearcher\u003c\u0027_, _\u003e",
"documentation": {
"kind": "markdown",
"value": "Associated type for `\u003c[char; N] as Pattern\u003c\u0027a\u003e\u003e::Searcher`."
},
"deprecated": false,
"sortText": "fffffff0", …
```
=> feat: Support for labelDetails completionItem

src/main/java/com/redhat/devtools/lsp4ij/features/foldingRange/LSPFoldingRangeBuilder.java
I have noticed that with language server which support folding like go, when IJ is indexing files, the language server is started and degrade performances of the IDE.
This PR marks the LSP folding as non dumAware to avoid starting language server while indexing.
=> perf: LSP folding must be computed outside dumb

src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowPanel.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorerLifecycleListener.java, src/main/java/com/redhat/devtools/lsp4ij/internal/ApplicationUtils.java
I have tested IJ EAP (> 2024.2) and LSP console panel doesn't appear when language server report log on IJ start.
This PR fixes this problem.
=> fix: show LSP console in IJ 2024.2

docs/DeveloperGuide.md
Only trivial changes: Fixed indentation, removed trailing spaces and balanced braces.
=> fix: Typos in `DeveloperGuide.md`

src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowPanel.java
I got this NPE in the LSP console when switching projects:
```
java.lang.NullPointerException: Cannot invoke "com.intellij.ui.content.Content.getComponent()" because the return value of "com.intellij.ui.content.ContentManager.getContent(int)" is null
at com.redhat.devtools.lsp4ij.console.LSPConsoleToolWindowPanel.lambda$showLog$1(LSPConsoleToolWindowPanel.java:464)
at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
at …
```
=> fix: prevent NPE in LSP console when switching projects

src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageClient.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageListener.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerDefinition.java
fix: send workspace/didChangeConfiguration with {} if configuration is empty
This PR:
* send `workspace/didChangeConfiguration` with {} if configuration textbox is empty and server starts
* send `workspace/didChangeConfiguration` if configuration textbox is not empty and server starts
* send `workspace/didChangeConfiguration` if configuration textbox ichanged and it is empty / or not empty
=> fix: send workspace/didChangeConfiguration with {} if configuration is empty

docs/DeveloperGuide.md, docs/LSPSupport.md, src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/java/com/redhat/devtools/lsp4ij/internal/ClientCapabilitiesFactory.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageClient.java
feat: support for 'workspace/configuration'
=> feat: support for 'workspace/configuration'

src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/FileNamePatternMappingExtensionPointBean.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/FileTypeMappingExtensionPointBean.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/LanguageMappingExtensionPointBean.java
fix: prevent from "implementation class is not specified" with documentMatcher
When documentMatcher is not declared in languageMapping, fileTypeMapping, etc, the following exception is thrown https://github.com/JetBrains/intellij-community/blob/def6433a5dd9f0a984cbc6e2835d27c97f2cb5f0/platform/core-api/src/com/intellij/serviceContainer/LazyExtensionInstance.java#L55
We catch this method, but it is cleaner to avoid calling getInstance if documentMatcher is not declared.
=> fix: prevent from "implementation class is not specified" with documentMatcher

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/java/com/redhat/devtools/lsp4ij/server/StreamConnectionProvider.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedStreamConnectionProvider.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockConnectionProvider.java
fix: rootUri must not end with a slash
* before the PR:
```
Params: {
"rootPath": "/C:/Users/azerr/IdeaProjects/pyright-langserver-for-pycharm-test/",
"rootUri": "file:///C:/Users/azerr/IdeaProjects/pyright-langserver-for-pycharm-test/",
```
* with vscode:
```
Params: {
"rootPath": "c:\\Users\\azerr\\IdeaProjects\\pyright-langserver-for-pycharm-test",
"rootUri": "file:///c%3A/Users/azerr/IdeaProjects/pyright-langserver-for-pycharm-test",
```
* after the PR:
```
Params: {
"rootPath": "C:/Users/azerr/IdeaProjects/pyright-langserver-for-pycharm-test",
"rootUri": "file:///C:/Users/azerr/IdeaProjects/pyright-langserver-for-pycharm-test",
```
=> fix: rootUri must not end with a slash

src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java, src/main/java/com/redhat/devtools/lsp4ij/commands/LSPCommandContext.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/LSPLazyCodeActionIntentionAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java, src/main/java/com/redhat/devtools/lsp4ij/settings/UserDefinedLanguageServerSettings.java, src/main/resources/messages/LanguageServerBundle.properties
feat: show notification error when command doesn't exist.
Here a sample with Clojure LSP when you click on CodeLens references:
=> feat: show notification error when command doesn't exist.

src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/ExtensionLanguageServerDefinition.java
fix: prevent NPE when isEnabled is called from plugin ls definition
=> fix: prevent NPE when isEnabled is called from plugin ls definition

src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/internal/ClientCapabilitiesFactory.java
feat: Diagnostic tags support
Here a demo with Lua LS which returns a diagntics tag  Unnecessary(1): 
Fixes #355 
Fixes #358
=> feat: Diagnostic tags support

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPFindActionTracker.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPFindUsagesHandlerFactory.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPFindUsagesProvider.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageTargetProvider.java, src/main/resources/META-INF/plugin.xml
fix: Enable Find Usages menu for custom file type different from TEXT and textmate
Fixes #351
Here a screenshot with Lua:
and the result:
please note that the right textarea is not filled correctly, I don't know why?
=> fix: Enable Find Usages menu for custom file type different from TEXT and textmate

src/main/java/com/redhat/devtools/lsp4ij/ui/IconMapper.java
With XML file path support: 
and with SumnekoLua (cc @CppCXY):
=> feat: display platform file icons on completion

src/main/java/com/redhat/devtools/lsp4ij/usages/LSPFindUsagesHandlerFactory.java, src/main/resources/META-INF/plugin.xml
fix: don't break custom "Find Usages" (like Java)
=> fix: don't break custom "Find Usages" (like Java)

src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPGoToAction.java
`AnActionEvent.getData(CommonDataKeys.VIRTUAL_FILE)` is a lazily computed value, which are forbidden to be retrieved on the EDT since 2024.2 (implicitly returning a null VirtualFile, and logging a stacktrace).
This caused the `Go To -> LSP *` actions to stay perpetually disabled.
Fixes #371
=> fix: actions not getting enabled on 2024.2

README.md
As requested by @angelozerr
https://github.com/rockofox/intellij-haskell-lsp/commit/8d699390213a0513ada37904a8e9d77eab50353e#commitcomment-143551798
=> docs: Add `intellij-haskell-lsp` to "Who is using LSP4IJ?" section in README

src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameHandler.java
fix: LSP rename is shown when Java variable is renamed.
In Qute  LS context we have Java file which is associated to the Qute LS and Qute can rename template file. 
As it is bound to Java files, when you try to rename a Java variable in inline mode, LSP rename is displayed too instead of processing inline rename variable:
This PR fix that.
=> fix: LSP rename is shown when Java variable is renamed.

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
Fixed a typo in LanguageServersRegistry that ignored SemanticTokensColorsProviders during language server registration from extension points.
=> fix: Semantic token color providers not being applied to language server definition

src/main/java/com/redhat/devtools/lsp4ij/internal/ClientCapabilitiesFactory.java, src/test/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LuaSemanticTokensTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPSemanticTokensFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockLanguageServer.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockTextDocumentService.java
fix: Support semantic token MultilineTokenSupport
Fixes #401
As IJ can support MultilineTokenSupport, this PR fill this capability and Lua language server doesn't report a large value.
Here the result:
This PR contains the first test with semantic token with this use-case. It would be very nice to create other tests in the future.
LSP4IJ ignores large values, we will see in the future if it needs to do that, but as I do not have a concrete use-case, LSP4IJ ignores it.
@CppCXY thanks so much for your great explanation!
=> fix: Support semantic token MultilineTokenSupport

src/main/resources/META-INF/plugin.xml
fix: No way to display the semantic token inspector tab once closed
Fixes #407
This PR forbids the close of the inspector like LSP console.
You can remove it from slide bar if you wish.
=> fix: No way to display the semantic token inspector tab once closed

docs/LSPSupport.md, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/DefaultSemanticTokensColorsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/SemanticTokensColorSettingsPage.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/SemanticTokensHighlightingColors.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/inspector/SemanticTokensInspectorToolWindowPanel.java, src/main/resources/META-INF/plugin.xml, src/main/resources/colorSchemes/SemanticTokensDark.xml, src/main/resources/colorSchemes/SemanticTokensHighConstrat.xml, src/main/resources/colorSchemes/SemanticTokensIntelliJLight.xml, src/main/resources/colorSchemes/SemanticTokensLight.xml, src/main/resources/messages/LanguageServerBundle.properties, src/test/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LuaSemanticTokensTest.java
feat: improve semantic tokens color attributes
This PR improve the color page with sample:
You can click on tree node to select attribute in the editor and select a token in the editor to select the proper node.
This PR also adds:
* color sheme for type parameter (I did the same thing than Java type parameter)
* the support of defaultLibrary for function
=> feat: improve semantic tokens color attributes

src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/inspector/SemanticTokensInspectorToolWindowPanel.java
Users should not be able to write in the semantic tokens editor (new content is deleted after being added). This PR makes the ST editor non-editable.
=> fix: make Semantic Tokens editor read-only

src/main/java/com/redhat/devtools/lsp4ij/features/LSPPsiElementFactory.java
fix: LSP textDocument/definition doens't open the file when range start / end are equals
Fixes #430
=> fix: LSP textDocument/definition doens't open the file when range start / end are equals

src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java
=> fix: Completion label matching always ends very early

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
fix: runAsync may throw exception and no log for it
Fixes #448
=> fix: runAsync may throw exception and no log for it

README.md
Add [Lean4ij](https://github.com/onriv/lean4ij), a plugin using LSP4IJ for connecting to the Lean4 lsp server, to the section  "Who is using LSP4IJ?" in readme.
=> docs: Add Lean4ij to "Who is using LSP4IJ?"

src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/ServerEnvCompletionTest.java
fix: support case sensitive for completion item which doesn't define a text range
This PR fixes https://github.com/OpenLiberty/liberty-tools-intellij/issues/897
Here a demo:
//cc @aparnamichael @turkeylurkey @mrglavas
=> fix: support case sensitive for completion item which doesn't define a text range

src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/CommandUtils.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedStreamConnectionProvider.java, src/test/java/com/redhat/devtools/lsp4ij/server/definition/launching/CommandUtilsTest.java
fix: trim spaces for user defined ls command.
This PR fixes the issue https://github.com/redhat-developer/lsp4ij/issues/513#issuecomment-2333854146
=> fix: trim spaces for user defined ls command.

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_findResourceForTest.java
fix: Invalid encoded URI like file://c%3A/ when dir contains '.'
Fixes #520
=> fix: Invalid encoded URI like file://c%3A/ when dir contains '.'

src/main/java/com/redhat/devtools/lsp4ij/console/actions/ApplyLanguageServerSettingsAction.java
Fixes internal usage in 2023.3.eap:
=> chore: don't use internal ActionToolbarImpl

README.md
This PR adds information about Ruff for PyCharm to the README.md file.
CC: @angelozerr
=> docs: Add `Ruff for PyCharm` to README.md

src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerProcessTreeNode.java
fix: IllegalArgumentException: Argument for @NotNull parameter 'fragment' of com/intellij/ui/SimpleColoredComponent.append must not be null
Fixes #473
I cannot reproduce the issue, but this PR initialize the displayName filed in the process tree node constructor. In this case displayName will be never null and we will avoid the error of the reported issue.
=> fix: IllegalArgumentException: Argument for @NotNull parameter 'fragment' of com/intellij/ui/SimpleColoredComponent.append must not be null

src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
=> fix: Handle null section as a request for the entire configuration object

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPSignatureHelpFeature.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPTypedHandlerDelegate.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/CompletionCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/SignatureHelpCapabilityRegistry.java
fix: triggered characters for completion/signatureHelp doesn't work with registerCapability
=> fix: triggered characters for completion/signatureHelp doesn't work with registerCapability

src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java
fix: textDocument/didClose is triggered upon the first close event when multiple views of the document are open
Fixes #574
=> fix: textDocument/didClose is triggered upon the first close event when multiple views of the document are open

src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPFeatureSupport.java
fix: prevent from NPE CancellationSupport
I cannot reproduce his issue, but @ia3andy reported me that he had this error sometimes:
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'cancellationSupport' of com/redhat/devtools/lsp4ij/features/codeAction/intention/LSPIntentionCodeActionSupport.doLoad must not be null
at com.redhat.devtools.lsp4ij.features.codeAction.intention.LSPIntentionCodeActionSupport.$$$reportNull$$$0(LSPIntentionCodeActionSupport.java)
at com.redhat.devtools.lsp4ij.features.codeAction.intention.LSPIntentionCodeActionSupport.doLoad(LSPIntentionCodeActionSupport.java)
at com.redhat.devtools.lsp4ij.features.codeAction.intention.LSPIntentionCodeActionSupport.doLoad(LSPIntentionCodeActionSupport.java:43)
at …
```
=> fix: prevent from NPE CancellationSupport

README.md
=> docs: Add Liberty Tools for IntelliJ to the list of projects.

docs/LSPApi.md, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java
feat: support isEnabled for file.  it gives per file-grain control for enable the server or not
Background from discussion https://github.com/redhat-developer/lsp4ij/discussions/582
=> feat: support isEnabled for file

src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java
Compare the oldValue to the newValue. In the case of a file name change only execute the rename code if the two names are different. 
Fixes #577
=> fix: compare two filenames before trying to rename the file

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/AbstractLSPFeature.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/DummyCodeVisionProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/DummyCodeVisionProviderFactory.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/CodeVisionEditorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeatureManager.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeatureType.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/FoldingEditorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/InlayHintsEditorFeature.java, src/main/resources/META-INF/plugin.xml
fix: No `textDocument/didOpen` sent when server is restarted
Fixes #585
=> fix: No `textDocument/didOpen` sent when server is restarted

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
fix: Address editor in RustRover's Memory View tab triggers LSP requests
Fixes #560
=> fix: Address editor in RustRover's Memory View tab triggers LSP requests

src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/SeverityMapping.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/ui/IconMapper.java
We just resolved this issue in Liberty Tools for IntelliJ: https://github.com/OpenLiberty/liberty-tools-intellij/issues/1092. I noticed a few instances of it in LSP4IJ.
=> fix: Use Locale.ROOT for capitalizing / decapitalizing locale insensitive strings.

src/main/java/com/redhat/devtools/lsp4ij/internal/editor/CodeVisionEditorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/FoldingEditorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/InlayHintsEditorFeature.java
This PR should fix the following error:
```
Error while calling ModificationStampUtil.clearModificationStamp(editor)
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:196)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at com.redhat.devtools.lsp4ij.internal.editor.CodeVisionEditorFeature.clearEditorCache(CodeVisionEditorFeature.java:69)
at com.redhat.devtools.lsp4ij.internal.editor.EditorFeatureManager.lambda$clearEditorCache$2(EditorFeatureManager.java:117)
at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.jav …
```
=> fix: Error while calling ModificationStampUtil.clearModificationStamp(editor)

src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/client/ProjectIndexingListener.java
fix: send didOpen before refreshing editors after a project indexing
=> fix: send didOpen before refreshing editors after a project indexing

src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDocumentSymbolFeature.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/DocumentSymbolData.java
Issue 618 - This provides a simple implementation of **Next/Previous Method** actions based on the existing structure view implementation by returning text offsets for name identifiers of methods and functions from the structure view. Ideally it would be implemented via `MethodNavigationOffsetProvider` -- and perhaps it should be -- but the only down-side to this approach is that when the **Previous Method** action is triggered from the first method/function in the file, it does navigate to the beginning of the file because text offset 0 is returned for other elements.
=> feat: Add support for Next/Previous Method actions

src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionProposal.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeatureManager.java, src/main/resources/templates/typescript-language-server/settings.json
fix: Method/function completions don't (consistently?) use an insert handler with parens for args
Fixes #610
=> fix: Method/function completions don't (consistently?) use an insert handler with parens for args

src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionProposal.java
fix: Inserted completions for methods/functions still don't include argument parens consistently
Fixes #627
=> fix: Inserted completions for methods/functions still don't include argument parens consistently

src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionProposal.java
fix: Inserted completions for methods/functions still don't include argument parens consistently (2)
Fixes #627
=> fix: Inserted completions for methods/functions still don't include argument parens consistently (2)

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/features/declaration/LSPDeclarationSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/implementation/LSPImplementationSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/navigation/LSPDefinitionSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/typeDefinition/LSPTypeDefinitionSupport.java
Issue 628 - When available, the target selection range should be used from the location link instead of the target range. That helps place the caret at the beginning of the target name identifier instead of the beginning of the entire target declaration. This logic has been extracted into a utility method, and all existing implementations of the same logic now use that method.
=> fix: Make go to definition/declaration/implementation target the name identifier (issue 628)

src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPGoToAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/declaration/LSPGoToDeclarationAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/implementation/LSPGoToImplementationAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/references/LSPGoToReferenceAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/typeDefinition/LSPGoToTypeDefinitionAction.java, src/main/resources/messages/LanguageServerBundle.properties
fix: IJ can freeze with execution of LSP References action
Fixes #634
The PR execute the LSP request (ex : textDocument/references) in an background task which avoids freezing IJ when request is called. Thebackground task should be cancellable.
=> fix: IJ can freeze with execution of LSP References action

src/main/java/com/redhat/devtools/lsp4ij/settings/ui/LanguageServerPanel.java
Those components have their own scrolling, and the nested scrolling mechanisms were causing issues with keyboard navigation, e.g., page up/down, etc., and other features such a Find (Ctrl+F). Without the surrounding scroll panes, it was also important that they be added so that they fill their available space vertically.
=> fix: Fixed an issue with the JSON text editors caused by them being in scroll panes

src/main/java/com/redhat/devtools/lsp4ij/features/progress/LSPProgressManager.java
Hello. When I use `$/progress`, the detailed message is displayed on the front.
The detailed message is displayed as `text2` in the [IntelliJ ProgressIndicator API](https://github.com/JetBrains/intellij-community/blob/56c38a555ee36467a9ac171f074d4d15d89a83a4/platform/core-api/src/com/intellij/openapi/progress/ProgressIndicator.java#L149).
The LSP title and message seem to correspond to the following:
| LSP | IntelliJ API |
|--------|--------|
| title | ProgressIndicator.text() |
| message | ProgressIndicator.text2() | 
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgress
=> fix: Show progress messages in detail

src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java, src/main/resources/META-INF/plugin.xml
This is a reissue of PR #639 which ran into issues with rebase/merge against main. The same comments in that PR apply here. The only differences are additional comments added to describe behavior in relatively recent vs. older IDE version and to be more clear about what's happening when `result.stopHere()` is called.
=> feat: Omit word completions (by default) when there are completions from the language server (issue 638)

src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/java/com/redhat/devtools/lsp4ij/client/SettingsHelper.java, src/test/java/com/redhat/devtools/lsp4ij/client/SettingsHelperTest.java
This is my attempt to fix #648 
My knowledge about LSP and its different language servers is very limited. Atleast for the faulty request shown in the issue and the configuration listed there this will now return the correct values.
=> fix: Allow requesting scalar values in workspace/configuration

src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingAppLifecycleListener.java
This PR tries to fix https://github.com/redhat-developer/lsp4ij/issues/660 (I cannot reproduce it).
The same error has been reported here https://github.com/EmmyLua/Intellij-EmmyLua2/issues/11
*
=> fix: register ProjectIndexingActivityHistoryListener on appFrameCreated

src/main/resources/META-INF/plugin.xml
Testing with a local pre-release build of LSP4IJ, I noticed that it was interfering with the same EP implementation in another language, and debugging a bit, I could see that LSP4IJ's was slotted in before that other one. By explicitly specifying `order="last"`, it is guaranteed to execute after all other EPs that don't also register themselves as `last` (at which point it's just about the plugin loading order).
=> feat: Made the LSP `typeDeclarationProvider` specify `order="last"` to help ensure that it will be invoked after other implementations

src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java
Minor enhancement to the earlier LSP code completion enhancement such that word completions are not shown on auto-completion or odd completion trigger counts. This means that pressing **Ctrl+Space** repeatedly will now toggle word completions on and off but they won't be shown when there are LSP-based completions on auto-complete or initial explicit completion trigger.
Here's an example of the behavior with this change where you can see that there are not word completions by default, but pressing **Ctrl+Space** will toggle them on and off:
=> feat: Allow **Ctrl+Space** to toggle whether or not word completions are displayed

src/main/java/com/redhat/devtools/lsp4ij/features/workspaceSymbol/LSPWorkspaceTypeDeclarationProvider.java
Changed the return value to `null` when we cannot service the request via LSP. That matches the contract according to its JavaDoc.
=> fix: Implementations must return `null` and not an empty array to indicate that they cannot service the request

src/main/java/com/redhat/devtools/lsp4ij/features/workspaceSymbol/LSPWorkspaceImplementationsSearch.java
fix: ensure executing Query LSP implementation in ReadAction
The ReadAction is required when element.isValid() or element.getContaingFile() is called when element is a TreeElement (ex: Qute token).
=> fix: ensure executing Query LSP implementation in ReadAction

src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/AbstractLSPJsonSchemaFileSystemProvider.java
Unfortunately I can't use `reloadPsi()` for two reasons:
1. There's not guaranteed to be a non-null `Project` when the JSON schema is loaded because it's loaded via a project-independent extension point.
2. `reloadPsi()` uses `FileManagerImpl` which is annotated as `@ApiStatus.Internal` and therefore almost certainly won't be accepted by JetBrains in a new plugin version submission. That likely needs to change to do something different, perhaps just what I'm doing here with a two-phase VFS refresh.
=> fix: Restoring VFS refresh of bundled JSON schema file

src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/AbstractLSPJsonSchemaFileProvider.java
Otherwise this could result in an effective NPE thrown by the `@NotNull` annotation at runtime.
=> fix: Changed `file` to be `@Nullable` since a `null` value could be provided to the method

src/main/java/com/redhat/devtools/lsp4ij/usages/LSPExternalReferencesFinder.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSearcher.java
fix: process element usages under ReadAction
Fixes #708
=> fix: process element usages under ReadAction

src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowPanel.java
fix: NPE in LSPConsoleToolWindowPanel when running against latest Zig Language Server builds
Fixes #740
=> fix: NPE in LSPConsoleToolWindowPanel when running against latest Zig Language Server builds

docs/LSPApi.md, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionProposal.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/SnippetTemplateFactory.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/SnippetTemplateLoader.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/SnippetTemplateSegment.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/ClientConfigurableLanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/ClientConfigurationSettings.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedCompletionFeature.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedWorkspaceSymbolFeature.java, src/main/resources/jsonSchema/clientSettings.schema.json, src/main/resources/templates/clojure-lsp/clientSettings.json, src/main/resources/templates/gopls/clientSettings.json, src/main/resources/templates/jdtls/clientSettings.json, src/main/resources/templates/lemminx/clientSettings.json, src/main/resources/templates/metals/clientSettings.json, src/main/resources/templates/rust-analyzer/clientSettings.json, src/main/resources/templates/sourcekit-lsp/clientSettings.json, src/main/resources/templates/typescript-language-server/clientSettings.json, src/main/resources/templates/vscode-css-language-server/clientSettings.json, src/main/resources/templates/vscode-html-language-server/clientSettings.json, src/test/java/com/redhat/devtools/lsp4ij/features/completion/CssCompletionClientConfigTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/SnippetTemplateLoaderTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/TypeScriptCompletionClientConfigTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCompletionClientConfigFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockLanguageServer.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockLanguageServerDefinition.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockTextDocumentService.java
This is a fresh branch-based PR as a replacmeent for #738.
As stated/shown in #718, the editor template that is currently started when accepting a code completion that is a method/function invocation ~~with a single argument~~ is quite disruptive to the standard editor flow. ~~This PR adds a new client configuration option, `completion.useTemplateForSingleArgument`, that, when disabled (enabled by default for backward-compatibility), instead just places the caret into the invocation arguments so that the user can populate them as they would in any of JetBrains' natively-supported language editors. I've also updated all existing language server definition templates to disable editor templates in this case so that the "default" behavior for newly-created language server definitions is the …
=> feat: Allow disabling of editor templates when accepting method/function invocation completions (fixes #718)

src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/java/com/redhat/devtools/lsp4ij/client/SettingsHelper.java, src/test/java/com/redhat/devtools/lsp4ij/client/SettingsHelperTest.java
=> fix: Allow requesting flat scalar values in workspace/configuration

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/dap/configurations/DAPServerMappingsPanel.java, src/main/java/com/redhat/devtools/lsp4ij/dap/configurations/DAPSettingsEditor.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterDescriptorFactory.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterDescriptorFactoryListener.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterManager.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/userdefined/UserDefinedDebugAdapterDescriptorFactory.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/DebugAdapterDescriptorFactoryConfigurable.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/DebugAdapterDescriptorFactoryListConfigurable.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/UserDefinedDebugAdapterDescriptorFactorySettings.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/DAPConnectingServerConfigurationPanel.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/DebugAdapterDescriptorFactoryPanel.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/DebugAdapterDescriptorFactoryView.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/NewDebugAdapterDescriptorFactoryDialog.java, src/main/java/com/redhat/devtools/lsp4ij/settings/UserDefinedLanguageServerSettings.java, src/main/java/com/redhat/devtools/lsp4ij/settings/ui/EditJsonSchemaDialog.java, src/main/java/com/redhat/devtools/lsp4ij/settings/ui/LanguageServerPanel.java, src/main/java/com/redhat/devtools/lsp4ij/settings/ui/ServerMappingsPanel.java, src/main/resources/META-INF/plugin.xml, src/main/resources/dap/templates/go-delve/attach.json, src/main/resources/messages/DAPBundle.properties
feat: provide UI to define DAP descriptor factory
Now it is possible to define Debug Adapter server in global settings:
After that we can use it in the launch:
We can also click on "create new" to open the dialog and fill it:
=> feat: provide UI to define DAP descriptor factory

src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/AbstractLSPExtendWordSelectionHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPCodeBlockBodySelectioner.java, src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPCodeBlockExtendWordSelectionHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPCodeBlockSelectioner.java, src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPCodeBlockStatementGroupSelectioner.java, src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPExtendWordSelectionHandler.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/lsp4ij/features/selectionRange/TypeScriptSelectionersTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPSelectionersFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockTextDocumentService.java
Previously we added support for the IDE's `extendWordSelectionHandler` using the LSP `textDocument/selectionRange` feature. That effectively allowed the user to extend and shrink the editor selection based on the document's syntax tree nodes with additional provisions to extend to full lines as appropriate. Natively-supported languages in JetBrains IDEs also include other _selectioners_ (not my term; see `com.intellij.codeInsight.editorActions.wordSelection.AbstractWordSelectioner`) to participate in this syntax-aware selection process that are not directly reflected in the document's AST. Two of the most useful ones are for selection of a _statement group_ -- a contiguous span of statements in the same code block with no intermediate blank lines -- and selection of all full lines within …
=> feat: Statement group and code block selectioners

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/AbstractLSPDeclarativeInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPDeclarativeInlayActionHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPDeclarativeInlayHintProvidersFactory.java, src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/CodeVisionEditorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/DeclarativeInlayHintsEditorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeatureManager.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeatureType.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/FoldingEditorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/InlayHintsEditorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/InlayHintCapabilityRegistry.java, src/main/resources/META-INF/plugin.xml, src/main/resources/messages/LanguageServerBundle.properties
- ~~Completely remove the dependency on the deprecated inlay hints API.~~ non-goal for this PR, it's needed for color hints
- Migrate inlay hints support to the declarative API
- Fix the double inlay hints bug
- https://github.com/redhat-developer/lsp4ij/issues/606, primary goal of this PR
- https://github.com/redhat-developer/lsp4ij/issues/382, as a side effect of the rendering being completely delegated to the intellij gui backend 
- ~~Inlay hint hover/click actions are not yet implemented~~ fixed
- ~~`textDocument/color` support is impossible through the declarative API due to its limitations, it only supports text nodes, and "trees" of text nodes~~ fixed, uses the old api
=> feat: Inlay hints refactor

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/dap/evaluation/DAPExpressionCodeFragment.java
fix: LSP doesn't work for external dependencies (like jars)
Fixes #782
=> fix: LSP doesn't work for external dependencies (like jars)

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/launching/UserDefinedLanguageServerSettings.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplate.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateDeserializer.java, src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerDefinition.java, src/main/resources/templates/sourcekit-lsp/template.json, src/test/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerDefinitionSerializerTest.java, src/test/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManagerTest.java
feat: store template id in the user ls definition
//cc @SCWells72 this PR provides `UserDedfinedLanguageServerDefinition#getTemplateId()` which is the original template id which have created the ls definition and null otherwise.
=> feat: store template id in the user ls definition

src/main/java/com/redhat/devtools/lsp4ij/dap/client/variables/DAPValue.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterVariableSupport.java
fix: Single/double quotes displayed not correctly in warch area when debug TypeScript file
Fixes #812
Here the result with inline value:
Here the result in the watch expression
=> fix: Single/double quotes displayed not correctly in warch area when debug TypeScript file

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowPanel.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java, src/main/java/com/redhat/devtools/lsp4ij/server/LSPProcessListener.java, src/main/java/com/redhat/devtools/lsp4ij/server/OSProcessStreamConnectionProvider.java, src/main/java/com/redhat/devtools/lsp4ij/server/StreamConnectionProvider.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/settings/actions/ReportErrorInLogAction.java, src/main/java/com/redhat/devtools/lsp4ij/settings/actions/ShowErrorLogAction.java, src/main/resources/messages/LanguageServerBundle.properties
feat: manage unexpectedly stop of server:
* when server start command is wrong
* when process is killed outside IJ
When server starts with wrong command, it throws a CannotStartProcessException. This exception is ignored now in the log and a notification error is shown:
Ex: `foo`
When server start command takes some times (ex: julia, java command) and the command is wrong, the server is now stopped.
Ex : with Julia LS
`julia -e "using LanguageServer; foo()"`
When process is killed outside IJ, the server is stopped.
=> feat: manage unexpectedly stop of server

src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugProcess.java, src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPBreakpointHandler.java
fix: DAP debugger doesn't support Run to Cursor
Fixes #840
Here a demo:
=> fix: DAP debugger doesn't support Run to Cursor

src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokensHighlightVisitor.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LazyHighlightInfo.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/SemanticTokensData.java
I encountered a consistent stutter (2-3 seconds long freezes) when working with huge generated files in zig. After analysing with a profiler, i've pinpointed the source to the `LSPSemanticTokensHighlightVisitor.highlightSemanticTokens` method, which blocks the EDT while it's adding every single `HighlightInfo` to the holder for the entire file, which is an expensive operation due to internal checks.
Additionally, for very large files (>50k lines), the `ProgressManager.checkCanceled();` call inside `SemanticTokensData.highlight`, along with the `HighlightInfo` creations also started being a major contributor (>30% sampler time) to the total freeze duration.
This pull request attempts to resolve these issues using the following steps:
1. `HighlightInfo` inside `SemanticTokensData.highlight` …
=> fix: Improved semantic highlighting performance for huge files

README.md
This PR adds the GroovyScript Plugin (https://github.com/IntegerLimit/GroovyScriptPlugin, https://plugins.jetbrains.com/plugin/25915-groovyscript/), to the list of plugins that utilise LSP4IJ.
This was requested in https://github.com/IntegerLimit/GroovyScriptPlugin/issues/9.
=> docs: Add GroovyScript to LSP4IJ Users

README.md
Reference: https://github.com/sashi0034/angel-intellij/issues/10
Add [AngelScript Language Server for IntelliJ](https://plugins.jetbrains.com/plugin/26645-angelscript-language-server/) to README.md
=> docs: add angelscript language server for intellij

src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPCodeBlockExtendWordSelectionHandler.java
While I haven't been able to reproduce this, the only way it could have happened is if `effectiveOffset` was incremented to be the same as `editorText.length()`, so I've made the logic defensive against that situation, terminating the loop before it reaches that point.
=> fix: Prospective fix for an `IndexOutOfBoundsException` (fixes #884)

src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokenType.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokenTypes.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticToken.java
This will need to be made configurable as part of #871.
=> fix: Added (hard-coded) support for SourceKit LSP's `identifier` semantic token type which should be interpreted as being a declaration.

README.md
docs: add "Meet LSP4IJ, a new Debug Adapter Protocol for JetBrains-based IDEs" article.
=> docs: add "Meet LSP4IJ, a new Debug Adapter Protocol for JetBrains-based IDEs" article.

src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPFeatureSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/CodeLensData.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensEditorFactoryListener.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/UnresolvedCodeLensViewportContext.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSearcher.java, src/main/resources/META-INF/plugin.xml
fix: Only call codelens/resolve for codelens in viewport
Fixes #141
=> fix: Only call codelens/resolve for codelens in viewport

src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewModel.java
perf: Do not clear the document symbol cache when the view is disposed.
=> perf: Do not clear the document symbol cache when the view is disposed.

src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticTokensFileViewProviderHelper.java
Changed a synchronized hashmap that is shown by a user-provided thread dump to be causing (or at least likely contributing to) a deadlock to be a concurrent hashmap with a much more forgiving locking model. If this doesn't resolve the issue, we likely need to try an unsynchronized hashmap to see if that resolves the deadlock, then determine the correct safe concurrency model for that data.
=> fix: Prospective fix for a deadlock observed by a user helping to test the semantic tokens enhancements.

src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewModel.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokensHighlightVisitor.java
perf: cancel LSP documentSymbol+semanticTokens only when file has changed
=> perf: cancel LSP documentSymbol+semanticTokens only when file has changed

src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/UnresolvedCodeLensViewportContext.java, src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPClientSideOnTypeFormattingTypedHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPServerSideOnTypeFormattingHelper.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticTokensFileViewProviderHelper.java
fix: do some performance improvement:
* avoid executing on type formatting (client, server side) when project are indexing otherwise it freezes the editor when you type something.
* remove the wait with timeout in LSPColorProvider (I already did that for inlay hint) because otherwise there are too many refresh of the editor. /cc @FalsePattern
=> fix: do some performance improvement

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingManager.java
=> fix: use language substitor

src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPExternalAnnotator.java
fix: duplicate errors when PsiFile has several files.
Ex: for Qute template file which substitute HTML file, there are 2 Psi files : HTMLFileImpl and QuteFileImpl which reports errors twice.
=> fix: duplicate errors when PsiFile has several files.

src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPBreadcrumbsRefreshListener.java, src/main/resources/META-INF/plugin.xml
This addresses an issue with the new LSP-based sticky lines feature where the IDE would query the `breadcrumbsInfoProvider` for sticky line info before the language server has started and therefore before breadcrumbs are available.
It adds a `postStartupActivity` that is invoked when a project is first opened that registers a `LanguageServerLifecycleListener` so that, when a language server's status is changed to `started`, sticky lines for open editor tabs for that language server can be refreshed. This has to happen in a bit of an indirect manner, though. Rather than talk through it here, it's probably best to defer to the code itself.
=> fix: Ensure that breadcrumbs/sticky lines are queried for files in open editor tabs after a language server starts

src/main/java/com/redhat/devtools/lsp4ij/ClosedDocument.java, src/main/java/com/redhat/devtools/lsp4ij/LSPDocumentBase.java, src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/OpenedDocument.java, src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDiagnosticFeature.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticsForServer.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/SeverityMapping.java, src/main/java/com/redhat/devtools/lsp4ij/features/inspection/LSPLocalInspectionTool.java, src/main/java/com/redhat/devtools/lsp4ij/features/inspection/LSPLocalInspectionToolBase.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/TextDocumentServerCapabilityRegistry.java, src/main/resources/META-INF/plugin.xml, src/main/resources/inspectionDescriptions/LSPLocalInspectionTool.html
"Code | Inspect Code" does not report syntax errors
Fixes #476
With this PR whenyou click on `Inspect Code` hyperlink:
It execute the local inspectionand show LSP result:
=> fix: "Code | Inspect Code" does not report syntax errors

docs/LSPSupport.md, docs/UserGuide.md, src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java, src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java, src/main/java/com/redhat/devtools/lsp4ij/LSPRequestConstants.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDiagnosticFeature.java, src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRefactoringListener.java, src/main/java/com/redhat/devtools/lsp4ij/inspections/LSPLocalInspectionTool.java, src/main/java/com/redhat/devtools/lsp4ij/inspections/LSPLocalInspectionToolBase.java, src/main/java/com/redhat/devtools/lsp4ij/internal/ClientCapabilitiesFactory.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DiagnosticCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/TextDocumentServerCapabilityRegistry.java, src/main/resources/META-INF/plugin.xml
fix: Support `textDocument/diagnostics`
Fixes #933
=> fix: Support `textDocument/diagnostics`

README.md
I’ve just realized that the URL for my language server in my previous pull request (https://github.com/redhat-developer/lsp4ij/pull/875) appears to be incorrect. I sincerely apologize for the mistake.
=> docs: fix url for angelscript language server

docs/user-defined-ls/docker-language-server.md
1. I did some copy/paste and the numbers incorrectly started at 3 instead of 1. :P
2. The language server is called "Docker Language Server" and not "Dockerfile Language Server".
=> fix: Docker documentation typos and bullet ordering

docs/LSPSupport.md, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPReferencesFeature.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/ClientConfigurationSettings.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedClientFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedReferencesFeature.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPExternalReferencesFinder.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSearcher.java, src/main/resources/jsonSchema/clientSettings.schema.json
Hopefully this one should be quite straightforward, but I'll add a few comments in the PR itself.
Here's an example of **Find Usages** with the feature flag disabled per its default setting:
and here it is explicitly enabled via client config picking up an external reference to TypeScript in an HTML file:
=> feat: Restoring external references search as an opt-in feature that's disabled by default.

src/main/java/com/redhat/devtools/lsp4ij/ClosedDocument.java, src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java, src/main/java/com/redhat/devtools/lsp4ij/LSPDocumentBase.java, src/main/java/com/redhat/devtools/lsp4ij/LSPFileSupport.java, src/main/java/com/redhat/devtools/lsp4ij/OpenedDocument.java, src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensEditorFactoryListener.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticsForServer.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPBreadcrumbsRefreshListener.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokensHighlightVisitor.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/DeclarativeInlayHintsEditorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeatureManager.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/InlayHintsEditorFeature.java
As soon as there is a publish/pull diagnostics, `DaemonCodeAnalyzer.getInstance(project).restart(file)` to refresh LSPDiagnosticAnnotator is called which can is bad for performance.
Most of the time, I noticed that LSPDiagnosticAnnotator is refreshed (if publish / pull diagnostic are fast) without having to call 
`DaemonCodeAnalyzer.getInstance(project).restart(file)`.
This PR avoids if possible to call `DaemonCodeAnalyzer.getInstance(project).restart(file)` by following those strategies:
* if publish diagnostic doesn't change (ex: you are typing a lot of spaces in the same line), `DaemonCodeAnalyzer.getInstance(project).restart(file)`  is never called.
*  debounce this call and cancel the call if the LSPDiagnosicAnnotator has already displayed the diagnostic
*  use this debounce (which …
=> perf: too many call of DaemonCodeAnalyzer.getInstance(project).restart(file)

src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/LSPLazyCodeActionIntentionAction.java, src/test/java/com/redhat/devtools/lsp4ij/features/codeAction/WebFilterQuickFixTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCodeActionFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockLanguageServer.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockTextDocumentService.java
test: provide test case for Jakarta quick fixes
=> test: provide test case for Jakarta quick fixes

src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java, src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/features/LSPPsiElement.java, src/main/java/com/redhat/devtools/lsp4ij/features/LSPPsiElementFactory.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeBlockProvider/LSPCodeBlockProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/CodeLensData.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/CompletionProposalTools.java, src/main/java/com/redhat/devtools/lsp4ij/features/declaration/LSPGoToDeclarationAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkGotoDeclarationHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/AbstractLSPFormattingService.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingParams.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/hierarchy/LSPHierarchyItemPsiElement.java, src/main/java/com/redhat/devtools/lsp4ij/features/hierarchy/LSPHierarchyNodeDescriptor.java, src/main/java/com/redhat/devtools/lsp4ij/features/hierarchy/LSPHierarchyProviderBase.java, src/main/java/com/redhat/devtools/lsp4ij/features/hierarchy/LSPHierarchyTreeStructureBase.java, src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightPsiElement.java, src/main/java/com/redhat/devtools/lsp4ij/features/implementation/LSPGoToImplementationAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRenamePsiElementProcessor.java, src/main/java/com/redhat/devtools/lsp4ij/features/references/LSPGoToReferenceAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/typeDefinition/LSPGoToTypeDefinitionAction.java, src/main/java/com/redhat/devtools/lsp4ij/hint/LSPNavigationLinkHandler.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSupport.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsagesManager.java
fix: Integrate fixes from forked (Huly Code) LSP4IJ (null checking)
See #959
This PR fixes Nullable annotations and some potential NullPointerException based on the Huly-Code fork of LSP4IJ
=> fix: Integrate fixes from forked (Huly Code) LSP4IJ (null checking)

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/test/java/com/redhat/devtools/lsp4ij/features/formatting/TypeScriptCustomLanguageServerEditorImprovementsTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/formatting/TypeScriptEditorImprovementsTest.java
The default TextMate enter-between-braces behavior differs between 2023.3 and 2024.1+. In 2023.3, typing enter between braces/brackets/parens such as:
```
values: [<typeEnterHere>]
```
would result in:
```
values: [
]
```
wheres in 2024.1-2025.1 (and presumably going forward), it results in:
```
values: [
]
```
That was causing a few tests that confirm the default TextMate enter-between-braces behavior when the enhanced enter-between-braces handler is disabled to fail.
I've updated these test expectations so that it's based on the host IDE version. Once 2023.3 support is dropped from LSP4IJ, this branching logic based on host IDE version can be removed and the 2024.1+ test expectations can be used.
=> fix: Default TextMate enter-between-braces behavior test expectation fixes for 2024.1+

src/main/resources/META-INF/plugin-telemetry.xml, src/main/resources/META-INF/plugin-textmate.xml, src/main/resources/META-INF/plugin.xml
chore: declare empty config file for optional plugins.
=> chore: declare empty config file for optional plugins.

src/main/java/com/redhat/devtools/lsp4ij/ClosedDocument.java, src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java, src/main/java/com/redhat/devtools/lsp4ij/LSPDocumentBase.java, src/main/java/com/redhat/devtools/lsp4ij/LSPFileSupport.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/OpenedDocument.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/FileUriSupport.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDiagnosticFeature.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticsForServer.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DiagnosticCapabilityRegistry.java, src/test/java/com/redhat/devtools/lsp4ij/features/diagnostics/RustDiagnosticsTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCodeActionFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCodeInsightFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPDiagnosticsFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockLanguageServer.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockTextDocumentService.java
fix: Pull diagnostics overwriting publish diagnostics
Fixes #968
=> fix: Pull diagnostics overwriting publish diagnostics

src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java, src/main/resources/templates/metals/settings.json
fix: use the same new conf of metals.ls vscode
@tribbloid LSP4IJ used an out of date Server Configuration settings. This PR fixes that and now semantic tokkens and inlay hint should work:
To test that:
* install nighty build
* update Server Configuration 
with this content:
```json
{
"metals": {
"disableReleaseNotes": false,
"serverVersion": "1.5.2",
"serverProperties": [
"-Xmx2G",
"-XX:+UseZGC",
"-XX:ZUncommitDelay=30",
"-XX:ZCollectionInterval=5",
"-XX:+IgnoreUnrecognizedVMOptions"
],
"coursierMirror": "",
"excludedPackages": [],
"inlayHints": {
"inferredTypes": {
"enable": true
},
"implicitArguments": {
"enable": true
},
"implicitConversions": {
"enable": true
},
"typeParameters": {
"enable": true
},
"hintsInPatternMatch": {
"enable": true
}
},
"javaHome": "",
"metalsJavaHome": "", …
```
=> fix: use the same new conf of metals.ls vscode

README.md
Adding LSP4IJ user to the list for Smart Data Lake Builder (SDLB) project. 
I would like to wait for Monday 28th April, 11:30AM UTC time to confirm it is ok with my team.
=> docs: add Smart Data Lake Builder to users list

src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewModel.java
fix: Don't force file support creation with document symbol
=> fix: Don't force file support creation with document symbol

src/main/resources/templates/dockerfile-language-server/template.json
The default path for Compose is `compose.yaml` and `compose.yml` so we should add those to the Docker Language Server as well.
=> fix: Include compose.yaml and compose.yml to the Docker Language Server

src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkDocumentationProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkGotoDeclarationHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkPsiElement.java, src/main/resources/META-INF/plugin.xml
fix: Document link will not open an external browser or show a tooltip
Fixes #1001
=> fix: Document link will not open an external browser or show a tooltip

docs/user-defined-ls/docker-language-server.md, src/main/resources/templates/dockerfile-language-server/initializationOptions.json, src/main/resources/templates/dockerfile-language-server/initializationOptions.schema.json
Document that the telemetry in the Docker Language Server is opt-out by default but can be configured as the user wishes during the initial setup of the language server.
Did I setup the `initializationOptions.schema.json` schema file correctly...? 🤔
=> docs: Add telemetry configuration and documentation for the Docker Language Server

docs/dap/DAPSupport.md, src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugProcess.java, src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPBreakpointHandler.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPClient.java
This PR should fix #996 and improve the breakpoint support by updating the breakpoint icon when DAP is working :
* when breakpoint is verified:
* when breakpoint is not verified:
=> fix: Debugpy ignoring changes to breakpoints

src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugProcess.java, src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPBreakpointHandler.java, src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPExceptionBreakpointsPanel.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPClient.java, src/main/java/com/redhat/devtools/lsp4ij/dap/configurations/DAPRunConfiguration.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterDescriptor.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DefaultDebugAdapterDescriptor.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/UserDefinedDebugAdapterServerSettings.java
This PR provides the capability to customize the enabled/disabled of exception breakpoint filters supported by the DAP server.
Once you will start the DAP server you can open the exception breakpoint menu:
This list of exception breakpoints is filled when the DAP server is initialized. The first time, the enabled/disabled of those breakpoints are managed by the DAP server (default value).
User can check/uncheck the exception to customize it. Those check/uncheck are persistent.
=> feat: make configurable DAP exceptions

docs/UserDefinedLanguageServerTemplate.md, src/main/resources/templates/lsp/clangd/installer.json, src/main/resources/templates/lsp/clojure-lsp/installer.json, src/main/resources/templates/lsp/erlang-ls/installer.json, src/main/resources/templates/lsp/rust-analyzer/installer.json
fix: use "unix"  instead of "linux"
=> fix: use "unix"  instead of "linux"

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
fix: NPE thrown when server returns a TextDocumentSyncOptions.save to null
Fixes #1076
=> fix: NPE thrown when server returns a TextDocumentSyncOptions.save to null

src/main/resources/templates/lsp/dockerfile-language-server/installer.json
1. There is another language server named the [Dockerfile Language Server](https://github.com/rcjsuen/dockerfile-language-server). This is _not_ that.
2. This language server provides features for Compose files and Bake files as well so this language server is _not_ only for Dockerfiles.
=> fix: Correct the name of the Docker Language Server

README.md
- Add link to Vala JetBrains Plugin in the `Who is using LSP4IJ` section of the `README.md`.
Suggested by @angelozerr  in https://github.com/Tbusk/vala-jetbrains-plugin/issues/30
=> feat: add Vala JetBrains Plugin to `Who is using LSP4IJ?` in README.md

src/main/resources/templates/lsp/vscode-css-language-server/installer.json
feat: use vscode-langservers-extracted for CSS language server
=> feat: use vscode-langservers-extracted for CSS language server

src/main/resources/templates/lsp/vscode-html-language-server/template.json
feat: set vscode html ls as dev
HTML Language Server will be visible only if the LSP4IJ is started in dev mode otherwise user will not see the language server.
As JetBrains provide a nice HTML support we don't need to show this language server to the user.
//cc @SCWells72
=> feat: set vscode html ls as dev

src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
fix: empty section must return the full server config
Language server from vscode-eslint get the configuration with empty section which must return the full config.
=> fix: empty section must return the full server config

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_toOffsetTest.java
Some LSP servers use Integer.MAX_VALUE as a special character position value to indicate "end of line" in position coordinates. LSPIJUtils.toOffset was not correctly handling this, which lead to for example received diagnostics notifications to be silently ignored.
=> fix: using integer max value as line end indicator

docs/UserDefinedLanguageServer.md, docs/user-defined-ls/stylelint-lsp.md, src/main/resources/templates/lsp/stylelint-lsp/installer.json, src/main/resources/templates/lsp/stylelint-lsp/settings.schema.json, src/main/resources/templates/lsp/stylelint-lsp/template.json
The correct tool name is "Stylelint" without a capital "L". This corrects the name in all places where it was wrong.
=> fix: Changed "StyleLint" to the correct case "Stylelint"

src/main/java/com/redhat/devtools/lsp4ij/features/workspaceSymbol/WorkspaceSymbolData.java
feat: Preview support for LSP workspace symbols
Here a sample with Symbol preview with rust.
//cc @manwithafox
=> feat: Preview support for LSP workspace symbols

docs/dap/DAPSupport.md, src/main/java/com/redhat/devtools/lsp4ij/dap/client/runInterminal/RunInTerminalManager.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/runInterminal/RunInTerminalService.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/runInterminal/external/ExternalTerminalService.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/runInterminal/external/LinuxExternalTerminalService.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/runInterminal/external/MacExternalTerminalService.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/runInterminal/external/WindowsExternalTerminalService.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/runInterminal/integrated/RunInIntegratedTerminalService.java
feat: Support runInTerminal (external only for Windows OS) request for DAP
This PR translate vscode code https://github.com/microsoft/vscode/blob/main/src/vs/platform/externalTerminal/node/externalTerminalService.ts which supports external terminal.
I have tested with windows but not with linux and mac.
@sbouchet @adietish is there any chance that you could test this PR (and debug it to fix issues on Linux/Mac), if yes I could explain how to test it.
Thanks
=> feat: Support runInTerminal (external only for Windows OS) request for DAP

src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplate.java
fix: don't show LS editor notif when a given plugin is installed
=> fix: don't show LS editor notif when a given plugin is installed

src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java
feat: Allow fully publishing diagnostics on documents not specified in the file associations?
Fixes #1232
=> feat: Allow fully publishing diagnostics on documents not specified in the file associations?

src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
fix: java.util.ConcurrentModificationException in LanguageServiceAccessor.getModificationTrackers
Fixes #1244
=> fix: java.util.ConcurrentModificationException in LanguageServiceAccessor.getModificationTrackers

src/main/java/com/redhat/devtools/lsp4ij/ClosedDocument.java, src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/OpenedDocument.java, src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DiagnosticCapabilityRegistry.java
fix: Display LSP diagnostics for opened documents which are not associated to a language server
Fixes #1232
=> fix: Display LSP diagnostics for opened documents which are not associated to a language server

src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java
fix: ignore CancellationException when LSP requets is cancelled
=> fix: ignore CancellationException when LSP requets is cancelled

src/main/java/com/redhat/devtools/lsp4ij/features/files/PathPatternMatcher.java, src/test/java/com/redhat/devtools/lsp4ij/features/files/FileSystemWatcherManagerTest.java
fix: workspace/didChangeWatchedFiles doesn't work with globPattern which defines a simple file name
Fixes #1273
=> fix: workspace/didChangeWatchedFiles doesn't work with globPattern which defines a simple file name

src/main/java/com/redhat/devtools/lsp4ij/dap/client/files/DeferredSourcePosition.java
fix: don't use internal OpenFileDescriptor#navigateInEditor
=> fix: don't use internal OpenFileDescriptor#navigateInEditor

src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPStackFrame.java
fix: Exception thrown when frame selection with source.name is null
Fixes #1294
=> fix: Exception thrown when frame selection with source.name is null

src/main/java/com/redhat/devtools/lsp4ij/dap/configurations/DAPRunConfiguration.java, src/main/java/com/redhat/devtools/lsp4ij/dap/configurations/options/EnvironmentVariablesDataConfigurable.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DefaultDebugAdapterDescriptor.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/templates/DAPTemplateDeserializer.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/NewDebugAdapterServerDialog.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateDeserializer.java, src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java, src/main/java/com/redhat/devtools/lsp4ij/templates/ServerTemplate.java, src/main/java/com/redhat/devtools/lsp4ij/templates/ServerTemplateJsonDeserializer.java, src/main/resources/templates/dap/buildx-dockerfile/template.json
fix: Environment variables of a DAP launch config are ignored
Fixes #1298
=> fix: Environment variables of a DAP launch config are ignored
