src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java, src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerListConfigurable.java
fix: fill LSP consoles with server which have no language mappings.
=> fix: fill LSP consoles with server which have no language mappings.

src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java, src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/operations/AbstractLSPInlayProvider.java, src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/operations/documentLink/LSPDocumentLinkAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/operations/documentLink/LSPDocumentLinkGotoDeclarationHandler.java, src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProvider.java, src/main/java/com/redhat/devtools/lsp4ij/operations/highlight/LSPHighlightUsagesHandlerFactory.java, src/main/java/com/redhat/devtools/lsp4ij/operations/navigation/LSPGotoDeclarationHandler.java
fix: fix language supported to use language substitor.
=> fix: fix language supported to use language substitor.

src/main/java/com/redhat/devtools/lsp4ij/commands/GsonManager.java
=> chore: remove reference to internal API com.intellij.ide.plugins.cl.PluginClassLoader

src/main/resources/META-INF/plugin.xml
feat: provides LSP hover support for all languages
=> feat: provides LSP hover support for all languages

docs/LSPSupport.md
=> fix: fix lsp support

src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionContributor.java
=> fix: Check CompletionItem.getKind() for null before using it.

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/operations/LSPInlayHintProvidersFactory.java
=> fix: show inlayhint for EAP

src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionProposal.java
=> fix: prevent from NPE when CompletionItem.textEdit field is not specified

src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionProposal.java
Let me know if you think one very long line is better. 
Fixes #54
=> fix: Check if CompletionOptions.getResolveProvider() is null before using it.

docs/DeveloperGuide.md, src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/operations/AbstractLSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/operations/documentLink/LSPDocumentLinkAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/operations/documentLink/LSPDocumentLinkGotoDeclarationHandler.java, src/main/java/com/redhat/devtools/lsp4ij/operations/documentation/LSPDocumentationProvider.java, src/main/java/com/redhat/devtools/lsp4ij/operations/highlight/LSPHighlightUsagesHandlerFactory.java, src/main/java/com/redhat/devtools/lsp4ij/operations/navigation/LSPGotoDeclarationHandler.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/ContentTypeToLanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/ServerFileTypeMapping.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/ServerMapping.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/FileTypeMappingExtensionPointBean.java, src/main/resources/META-INF/plugin.xml
feat: File Type mapping support.
=> feat: File Type mapping support.

src/main/java/com/redhat/devtools/lsp4ij/operations/color/ColorInlayPresentation.java, src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionProposal.java, src/main/java/com/redhat/devtools/lsp4ij/ui/IconMapper.java, src/test/java/com/redhat/devtools/lsp4ij/ui/IconMapperTest.java
=> feat: provide color icons for completion

src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionProposal.java
fix: Wrong snippet rendering with CSS language server
Fixes #67
=> fix: Wrong snippet rendering with CSS language server

src/main/java/com/redhat/devtools/lsp4ij/ui/IconMapper.java, src/test/java/com/redhat/devtools/lsp4ij/ui/IconMapperTest.java
fix: NPE when color is undefined.
=> fix: NPE when color is undefined.

gradle.properties, src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/resources/META-INF/plugin.xml
=> fix: remove dependency on the java plugin

src/main/java/com/redhat/devtools/lsp4ij/operations/completion/LSPCompletionProposal.java
fix: wrong position for completion snippet without tabstops
When a completion item doesn't define some tabstop or placeholder and the format is snippet, teh apply completion is wrong.
Given this CSS file:
```css
a {
col|
background-color: ;
}
```
Here a demo with master:
Here a demo with my PR:
=> fix: wrong position for completion snippet without tabstops

src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManager.java
=> fix: make loadTemplateStream return a BufferedInputStream

src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplate.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManager.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplates.java
=> chore: remove commons-io's IOUtils dependency

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java, src/main/java/com/redhat/devtools/lsp4ij/internal/IntelliJPlatformUtils.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplate.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManager.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplates.java, src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java, src/main/resources/templates/java/lemminx.md, src/main/resources/templates/template-ls.json
feat: add LemMinx as template language server in dev mode
=> feat: add LemMinx as template language server in dev mode

src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManager.java, src/main/resources/templates/template-ls.json
fix : Language server templates are empty
=> fix: Language server templates are empty

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java
By using typescript-language-server, the publish diagnostics from the language server report URI with `%` like  `"file:///c%3A/Users/azerr/IdeaProjects/untitled7/test.ts"`
```
[Trace - 17:58:38] Received notification 'textDocument/publishDiagnostics'
Params: {
"uri": "file:///c%3A/Users/azerr/IdeaProjects/untitled7/test.ts",
"diagnostics": [
{
"range": {
"start": {
"line": 1,
"character": 2
},
"end": {
"line": 1,
"character": 8
}
},
"severity": 1,
"code": 2551,
"source": "typescript",
"message": "Property \u0027charAB\u0027 does not exist on type \u0027\"\"\u0027. Did you mean \u0027charAt\u0027?",
"relatedInformation": [
{
"location": {
"uri": "file:///c%3A/Users/azerr/node_modules/typescript/lib/lib.es5.d.ts",
"range": {
"start": {
"line": 417,
"character": 4
},
"end": {
"line": 417, …
```
=> fix: decode URI if needed

src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
=> fix: restore LanguageServiceAccessor.getActiveLanguageServers(...)

src/main/resources/templates/node/typescript-language-server.md, src/main/resources/templates/template-ls.json
feat: add typescript language server as template in dev mode
=> feat: add typescript language server as template in dev mode

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/hint/LSPNavigationLinkHandler.java, src/main/java/com/redhat/devtools/lsp4ij/internal/SupportedFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/operations/diagnostics/LSPDiagnosticAnnotator.java, src/main/resources/META-INF/plugin.xml
feat: support for diagnostic related informations.
Here a demo with TypeScript ls:
=> feat: support for diagnostic related informations.

src/main/resources/templates/java/jdt.ls.md, src/main/resources/templates/java/lemminx.md, src/main/resources/templates/template-ls.json
=> feat: add eclipse.jdt.ls template (dev)

src/main/resources/templates/template-ls.json
=> feat: add scss support

src/main/resources/templates/template-ls.json
feat: associate JSX, TSX React files with typescipt language sever
See [here](https://github.com/typescript-language-server/typescript-language-server/blob/a00c1cc364b3bcdbab0cf2ac3d5b6e6adc4d9377/src/configuration/languageIds.ts#L28) for language Ids.
=> feat: associate JSX, TSX React files with typescipt language sever

src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java
fix: Failures to execute a code action are not reported
Fixes #121
With this PR when the execution of the command crashes on server side it display an error notification
=> fix: Failures to execute a code action are not reported

gradle.properties, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/redhat/devtools/lsp4ij/ServerMessageHandler.java, src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java
=> build: update minimum required IJ version to 2022.3

src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerListConfigurable.java
=> fix: override getActionUpdateThread() in LSP settings actions

src/main/java/com/redhat/devtools/lsp4ij/operations/LSPPsiElement.java, src/main/java/com/redhat/devtools/lsp4ij/operations/LSPPsiElementFactory.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageElementDescriptionProvider.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageTargetProvider.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageTriggeredPsiElement.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsagesManager.java, src/main/resources/META-INF/plugin.xml, src/main/resources/messages/LanguageServerBundle.properties
feat: improve LSP target of "Find Usages"
=> feat: improve LSP target of "Find Usages"

src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSearcher.java
=> fix: prevent NPE in LSPUsageSearcher.processElementUsages

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_getTokenRangeTest.java
chore: tests for LSPIJUtils#getTokenRange
=> chore: tests for LSPIJUtils#getTokenRange

src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageTargetProvider.java
fix: StringIndexOutOfBoundsException while editing file
Fixes #152
=> fix: StringIndexOutOfBoundsException while editing file

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/TypeScriptCompletionTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCodeInsightFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCodeInsightTestFixture.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCompletionFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPTestFixtureFactory.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/impl/LSPCodeInsightTestFixtureImpl.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/impl/LSPTestFixtureFactoryImpl.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockConnectionProvider.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockLanguageServer.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockLanguageServerDefinition.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockTextDocumentService.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockWorkspaceService.java
This PR provide a framework kind to test LSP features by providing a mock language server (like LSP4E does).
It provides just one test for completion (see https://github.com/redhat-developer/lsp4ij/pull/175/files#diff-aae8a28073ab27eecaab47288978997720fda23d0c98c897885c59e0a7a76d2c) but my plan is to write more tests in another PRs.
=> test: test completion

.github/workflows/ci.yml, build.gradle.kts, gradle/libs.versions.toml
=> build: add test coverage reporting

.github/workflows/changelog.yml
=> chore: bump changelog to 0.0.12

src/main/java/com/redhat/devtools/lsp4ij/ui/IconMapper.java, src/main/resources/images/nodes/template.svg, src/test/java/com/redhat/devtools/lsp4ij/ui/IconMapperTest.java
=> chore: remove template.svg, use the one from platform instead

codecov.yml
=> chore: silence codecov for a bit

codecov.yml
=> chore: disable codecov patch status

docs/LSPSupport.md, docs/UserGuide.md, docs/user-defined-ls/metals.md, src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java, src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/LSPRequestConstants.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerItem.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java, src/main/java/com/redhat/devtools/lsp4ij/features/files/PathPatternMatcher.java, src/main/java/com/redhat/devtools/lsp4ij/features/files/operations/FileOperationFilterMatcher.java, src/main/java/com/redhat/devtools/lsp4ij/features/files/operations/FileOperationMatcher.java, src/main/java/com/redhat/devtools/lsp4ij/features/files/operations/FileOperationsManager.java, src/main/java/com/redhat/devtools/lsp4ij/features/files/watcher/FileSystemWatcherManager.java, src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRefactoringListener.java, src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRenameFilesContext.java, src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRenameFilesContextHolder.java, src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRenamePsiElement.java, src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRenamePsiElementProcessor.java, src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/WorkspaceEditData.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java, src/main/java/com/redhat/devtools/lsp4ij/internal/SupportedFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/settings/actions/DisableLanguageServerErrorAction.java, src/main/java/com/redhat/devtools/lsp4ij/settings/actions/ReportErrorInLogAction.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/lsp4ij/features/files/FileSystemWatcherManagerTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/files/PathPatternMatcherTest.java
feat: Support for workspace/willRenameFiles
Fixes #194
=> feat: Support for Support for workspace/willRenameFiles

gradle.properties, src/main/resources/META-INF/plugin.xml
=> build: set pluginSinceBuild to 231 and fix typos in plugin description

src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/intention/LSPIntentionCodeActionSupport.java
fix: filter 'quickfix' code action for IJ intention
=> fix: filter 'quickfix' code action for IJ intention

src/main/java/com/redhat/devtools/lsp4ij/features/rename/DefaultPrepareRenameResultProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPPrepareRenameSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameHandler.java, src/main/resources/messages/LanguageServerBundle.properties
feat: invalid rename location should report an error message.
Here a demo with go ls:
=> feat: invalid rename location should report an error message.

src/main/java/com/redhat/devtools/lsp4ij/console/actions/ApplyLanguageServerSettingsAction.java
Fixes #228 
Link the balloon to the languageServerView so it is disposed at the same time
=> fix: Add explicit disposable to balloon

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java, src/test/java/com/redhat/devtools/lsp4ij/LSP4IJAssert.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_applyWorkspaceEdit_ClojureTest.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_applyWorkspaceEdit_GoTest.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_applyWorkspaceEdit_ScalaTest.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_applyWorkspaceEdit_TypeScriptTest.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_getTokenRangeTest.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_toOffsetTest.java
fix: Bad result after applying gopls' "Inline call to Println" code action
Fixes #203
=> fix: Bad result after applying gopls' "Inline call to Println" code action

src/main/resources/templates/template-ls.json
=> fix: update UD LS default command templates for Mac/Linux

src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java, src/main/resources/META-INF/plugin.xml
perf: Detail completion must be resolved on selected item
Fixes #248
=> perf: consume completionItem/resolve to resolve detail only when item is selected

src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameHandler.java
fix: don't show LSP rename dialog when a Java element is renamed
=> fix: don't show LSP rename dialog when a Java element is renamed

src/main/java/com/redhat/devtools/lsp4ij/JSONUtils.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageClient.java, src/test/java/com/redhat/devtools/lsp4ij/JSONUtils_findByPathTest.java
fix: List<Object> size should be the same than ConfigurationParams size.
=> fix: List<Object> size should be the same as ConfigurationParams size.

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_toOffsetTest.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_toPositionTest.java
fix: Support for invalid offset when LSP position is created
Fixes #241
=> fix: Support for invalid offset when LSP position is created

src/main/java/com/redhat/devtools/lsp4ij/launching/FileTypeSettings.java, src/main/java/com/redhat/devtools/lsp4ij/launching/ServerMappingSettings.java
=> fix: Apply button is not enabled when mappings change

src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRenamePsiElementProcessor.java
fix: `Rename File...` causes an NPE while consuming LSP 'workspace/willRenameFiles' request
Fixes #263
=> fix: `Rename File...` causes an NPE while consuming LSP 'workspace/willRenameFiles' request

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java
Also fixes some warnings in that file
=> fix: remove last internal API usage in LSPIJUtils

src/main/java/com/redhat/devtools/lsp4ij/LSPVirtualFileData.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerItem.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java, src/main/java/com/redhat/devtools/lsp4ij/commands/LSPCommandAction.java, src/main/java/com/redhat/devtools/lsp4ij/commands/LSPCommandContext.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/CodeActionData.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/LSPLazyCodeActionIntentionAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/intention/LSPIntentionCodeActionSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/quickfix/LSPLazyCodeActions.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticsForServer.java, src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java
feat: LSPCodeLensProvider and LSPInlayHintsProvider should be able to call server commands
Fixes #136
=> feat: LSPCodeLensProvider and LSPInlayHintsProvider should be able to call server commands

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java, src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRenamePsiElementProcessor.java, src/main/java/com/redhat/devtools/lsp4ij/features/signatureHelp/LSPParameterInfoHandler.java
Try to get document without read action
=> perf: Try to get document without read action

README.md, USAGE_DATA.md, build.gradle.kts, src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/actions/DeleteServerAction.java, src/main/java/com/redhat/devtools/lsp4ij/internal/LSPPostStartupActivity.java, src/main/java/com/redhat/devtools/lsp4ij/internal/telemetry/NoOpTelemetryService.java, src/main/java/com/redhat/devtools/lsp4ij/internal/telemetry/RedHatTelemetryService.java, src/main/java/com/redhat/devtools/lsp4ij/internal/telemetry/TelemetryManager.java, src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinitionListener.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageListener.java, src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerListConfigurable.java, src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerView.java, src/main/java/com/redhat/devtools/lsp4ij/telemetry/TelemetryService.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCodeInsightFixtureTestCase.java
=> build: make telemetry dependency optional

src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkGotoDeclarationHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPDocumentationProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/foldingRange/LSPFoldingRangeBuilder.java, src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightUsagesHandlerFactory.java, src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/refactoring/LSPRenamePsiElementProcessor.java, src/main/java/com/redhat/devtools/lsp4ij/features/signatureHelp/LSPParameterInfoHandler.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java, src/main/java/com/redhat/devtools/lsp4ij/internal/PromiseToCompletableFuture.java
fixes build failure https://github.com/redhat-developer/lsp4ij/actions/runs/9120847301/job/25078990651 caused by
https://github.com/JetBrains/intellij-community/commit/12e78f18d6352502c7cc942dc677f02bb9b8b257
=> fix: adapt to change in ProcessCanceledException hierarchy in 2024.2

src/main/resources/intentionDescriptions/Refactor/description.html
Namely, `Refactor/description.html`:
https://github.com/redhat-developer/lsp4ij/blob/2a9cf025118279982a8e3a6e55e9d04696a78b01/src/main/resources/intentionDescriptions/Refactor/description.html#L3-L4
=> fix: Copy-and-paste error in intention description

src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPDocumentationHelper.java, src/test/java/com/redhat/devtools/lsp4ij/features/documentation/TypeScriptHoverTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPHoverFixtureTestCase.java
=> test: provide LSP hover tests

src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCompletionFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPFormattingFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPRenameFixtureTestCase.java
=> chore: reduce mock server sleep time to speed tests up

README.md
Hi, congratulations on the release of LSP4IJ! I released [my plugin](https://plugins.jetbrains.com/plugin/24358-inga) on the marketplace, so please add me as an LSP4IJ user if you like. This plugin connects LSP4IJ to a local language server in a container. https://github.com/redhat-developer/lsp4ij/discussions/286#discussioncomment-9375571
=> docs: Add Inga plugin to README.md

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/GoCompletionTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/MicroProfileConfigPropertiesCompletionTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCompletionFixtureTestCase.java
fix: Problem with caret offset after completion apply with go
Fixes #311
=> fix: Problem with caret offset after completion apply with go

src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPDocumentationTargetProvider.java
perf: don't process LSP hover while indexing(dumb)
=> perf: don't process LSP hover while indexing(dumb)

src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java
While debugging LSP codelens to improve performance I noticed that LSPCodeLensProvider#computeCodeVision is called in NON read action. 
It means that when we get document, PsiFile it takes 2 locks to get ReadAction and more for other part of LSP codelens code.
This PR:
*  avoid taking lock for ReadAction to check if file is associated to a language server
* takes one read action to compte codelens, I follow the same idea than https://github.com/JetBrains/intellij-community/blob/def6433a5dd9f0a984cbc6e2835d27c97f2cb5f0/platform/lang-impl/src/com/intellij/codeInsight/hints/InlayHintsUtils.kt#L290
=> perf: open one read action to consume LSP codelens

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerManager.java, src/main/java/com/redhat/devtools/lsp4ij/launching/UserDefinedLanguageServerSettings.java
Diffs in a nutshell:
```diff
-languageSever
+languageServer
```
=> fix: Typos in `LanguageServerManager.java` and `UserDefinedLanguageServerSettings.java`

src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
fix: dont send workspace/didChangeConfiguration when server starts.
=> fix: dont send workspace/didChangeConfiguration when server starts.

src/main/java/com/redhat/devtools/lsp4ij/ui/IconMapper.java
feat: use AllIcons.Json.Object for Struct completion item kind
=> feat: use AllIcons.Json.Object for Struct completion item kind

src/test/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateDeserializerTest.java, src/test/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManagerTest.java
fix: fix test import for Windows OS
=> fix: fix test import for Windows OS

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionParams.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPTypedHandlerDelegate.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/AbstractLSPFormattingService.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingAndRangeBothService.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingOnlyService.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameHandler.java, src/main/resources/META-INF/plugin.xml, src/main/resources/messages/LanguageServerBundle.properties, src/test/java/com/redhat/devtools/lsp4ij/features/rename/QuteRenameTest.java
feat: Support for triggered chars in LSP completion support
Fixes #14
=> feat: Support for triggered chars in LSP completion support

docs/DeveloperGuide.md
=> docs: update special cases

src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/features/files/watcher/FileSystemWatcherManager.java, src/test/java/com/redhat/devtools/lsp4ij/features/files/FileSystemWatcherManagerTest.java
fix: use registration id to update workspace/didChangeWatchedFiles cache
Fixes #342
=> fix: use registration id to update workspace/didChangeWatchedFiles cache

src/main/resources/META-INF/plugin.xml
=> chore: Changelog for 0.0.2

docs/LSPSupport.md
=> docs: Mention `order=""` in `signatureHelp` section

README.md
=> docs: Add LSP4IJ article

src/main/java/com/redhat/devtools/lsp4ij/LSPFileSupport.java, src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/ServerMessageHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkGotoDeclarationHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPDocumentationLinkHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPDocumentationTarget.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentation/MarkdownConverter.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentation/markdown/LSPLinkResolver.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentation/markdown/SyntaxColorationCodeBlockRenderer.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentation/markdown/TextMateHighlighterHelper.java, src/main/java/com/redhat/devtools/lsp4ij/hint/LSPNavigationLinkHandler.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/lsp4ij/features/documentation/MarkdownConverterTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/documentation/MarkdownConverterWithPsiFileTest.java
feat: Support file link in hover
Fixes #376
@CppCXY here a demo with your Lua LS:
=> feat: Support file link in hover

src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokensRainbowVisitor.java
fix: Semantic highlighting consume a lot of CPU
Fixes #394
=> fix: Semantic highlighting consume a lot of CPU

src/main/java/com/redhat/devtools/lsp4ij/internal/ClientCapabilitiesFactory.java
=> fix: set token format in semantic highlighting capability

src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManager.java
=> fix: find templates directory when path contain spaces

README.md
=> docs: Add Pyright for PyCharm to project list

src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPDocumentationHelper.java
fix: Wrong code block renderer when documentation contains CLRF
Fixes #368
=> fix: Wrong code block renderer when documentation contains CLRF

src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPExternalAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkAnnotator.java
fix: Qute language server diagnotics are duplicated
Fixes #444
=> fix: Qute language server diagnotics are duplicated

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore: Changelog for 0.4.0

src/main/java/com/redhat/devtools/lsp4ij/client/LanguageClientImpl.java
fix: Semantic tokens attributes not applied on first start
Fixes #475
=> fix: Semantic tokens attributes not applied on first start

src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java, src/test/java/com/redhat/devtools/lsp4ij/commands/CommandExecutorTest.java
fix: IncorrectOperationException: Must not change document outside command or undo-transparent action
Fixes #480
=> fix: IncorrectOperationException: Must not change document outside command or undo-transparent action

src/main/java/com/redhat/devtools/lsp4ij/internal/LSPPostStartupActivity.java, src/main/java/com/redhat/devtools/lsp4ij/internal/telemetry/RedHatTelemetryService.java, src/main/java/com/redhat/devtools/lsp4ij/internal/telemetry/TelemetryManager.java, src/main/java/com/redhat/devtools/lsp4ij/telemetry/TelemetryEventName.java, src/main/java/com/redhat/devtools/lsp4ij/telemetry/TelemetryService.java, src/main/resources/META-INF/plugin.xml
=> chore: clean telemetry code

gradle.properties
=> chore: Bump to 0.5.0-SNAPSHOT

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore: Changelog for 0.5.0

src/main/resources/colorSchemes/SemanticTokensHighConstrat.xml, src/main/resources/colorSchemes/SemanticTokensHighContrast.xml
=> fix: color shemes file name

src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPGoToAction.java
perf: don't force the start language server for menu action
=> perf: don't force the start language server for menu action

gradle.properties, src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/features/LSPPsiElementFactory.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionProposal.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/DefaultPrepareRenameResultProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPPrepareRenameParams.java, src/main/java/com/redhat/devtools/lsp4ij/features/rename/LSPRenameHandler.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageTargetProvider.java, src/test/java/com/redhat/devtools/lsp4ij/LSP4IJAssert.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/BootstrapPropertiesCompletionTest.java, src/test/java/com/redhat/devtools/lsp4ij/features/rename/QuteRenameTest.java
feat: get word range at by using PsiFile
This PR should fix:
* https://github.com/redhat-developer/lsp4ij/issues/512
* https://github.com/OpenLiberty/liberty-tools-intellij/issues/946
* https://github.com/OpenLiberty/liberty-tools-intellij/issues/989
Here a demo:
=> feat: get word range at by using PsiFile

docs/DeveloperGuide.md, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/ServerMessageHandler.java, src/main/java/com/redhat/devtools/lsp4ij/server/CannotStartProcessException.java, src/main/java/com/redhat/devtools/lsp4ij/server/LSPProcessListener.java, src/main/java/com/redhat/devtools/lsp4ij/server/LanguageServerLogErrorHandler.java, src/main/java/com/redhat/devtools/lsp4ij/server/OSProcessStreamConnectionProvider.java, src/main/java/com/redhat/devtools/lsp4ij/server/ProcessDataProvider.java, src/main/java/com/redhat/devtools/lsp4ij/server/ProcessStreamConnectionProvider.java, src/main/java/com/redhat/devtools/lsp4ij/server/StreamConnectionProvider.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedStreamConnectionProvider.java, src/test/java/com/redhat/devtools/lsp4ij/mock/MockConnectionProvider.java
feat: Investigate using OSProcessHandler
Fixes #153
=> feat: Investigate using OSProcessHandler

src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java, src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java
chore: use CompletableFuture to wait after sending didOpen notification.
=> chore: use CompletableFuture to wait after sending didOpen notification.

src/main/resources/META-INF/plugin.xml
chore: add changelog for 0.6.0
=> chore: add changelog for 0.6.0

src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSearcher.java
fix: NullPointerException from Find Usages action in IntelliJ using LSP4IJ 0.6.0
Fixes #547
=> fix: NullPointerException from Find Usages action in IntelliJ using LSP4IJ 0.6.0

src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightUsagesHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightUsagesHandlerFactory.java
perf: cancel LSP highlight only if offset changed.
=> perf: cancel LSP highlight only if offset changed.

src/main/java/com/redhat/devtools/lsp4ij/LSPFileSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPDocumentationTargetProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPHoverParams.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPHoverSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPDocumentHighlightParams.java, src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightUsagesHandlerFactory.java, src/main/java/com/redhat/devtools/lsp4ij/features/navigation/LSPDefinitionParams.java, src/main/java/com/redhat/devtools/lsp4ij/features/navigation/LSPDefinitionSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/navigation/LSPGotoDeclarationHandler.java
perf: Unreasonnable amount of textDocument/definition requests sent on Ctrl/Cmd
Fixes #20
=> perf: Unreasonnable amount of textDocument/definition requests sent on Ctrl/Cmd

README.md
=> docs: add Intellij Gleam to list of projects

src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPFormattingFeature.java
Improvement to the API documentation as per #561
=> docs: Better javadoc in LSPFormattingFeature

docs/DeveloperGuide.md, gradle.properties, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDiagnosticFeature.java
chore: bump to 0.7.0 + minor fix for LSP diagnostic feature
=> chore: bump to 0.7.0 + minor fix for LSP diagnostic feature

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/CodeActionCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/CodeLensCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/CompletionCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DeclarationCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DefinitionCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DocumentColorCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DocumentFormattingCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DocumentHighlightCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DocumentLinkCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DocumentRangeFormattingCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/DocumentSymbolCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/FoldingRangeCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/HoverCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/ImplementationCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/InlayHintCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/ReferencesCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/RenameCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/SignatureHelpCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/TextDocumentServerCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/TypeDefinitionCapabilityRegistry.java
=> fix: hover dynamic options

docs/LSPApi.md, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java
feat: add canStopServerByUser LSP client feature
@kdvolder could you review this PR please (canStopServerByUser name is good? Javadoc is good?)
Thanks!
=> feat: add canStopServerByUser LSP client feature

docs/DeveloperGuide.md, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerItem.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/server/Lease.java, src/main/java/com/redhat/devtools/lsp4ij/server/ServerWasStoppedException.java
In relation to discussion https://github.com/redhat-developer/lsp4ij/discussions/558#discussioncomment-10847893
This has not been tested in any way, its more of POC and to help in making this long discussion maybe a bit more concrete, as well as trying to make it more clear what it is that I actually would like to see as an api to support a 'keep server alive' function.
=> feat: Proposed 'keepAlive' server lease style api.

src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionFeature.java, src/main/resources/META-INF/plugin.xml
=> chore: changelog for 0.7.0

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCodeActionFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCodeLensFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPCompletionFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDeclarationFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDefinitionFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDocumentColorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDocumentHighlightFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDocumentLinkFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPDocumentSymbolFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPFoldingRangeFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPFormattingFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPHoverFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPImplementationFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPInlayHintFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPReferencesFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPRenameFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPSignatureHelpFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPTypeDefinitionFeature.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/TextDocumentServerCapabilityRegistry.java
fix : synchronized client features creation to avoid loosing register capability.
=> fix: synchronized client features creation to avoid loosing register capability.

gradle.properties
=> chore: bump to 0.8.0-SNAPSHOT

.github/workflows/IJ-latest.yml, .github/workflows/IJ.yml, .github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
build: use gradle 4 in github actions
=> build: use gradle 4 in github actions

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
fix: dont disable server when project is closed.
=> fix: dont disable server when project is closed.

docs/LSPSupport.md, src/main/java/com/redhat/devtools/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerItem.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/client/ExecuteLSPFeatureStatus.java, src/main/java/com/redhat/devtools/lsp4ij/client/IndexAwareLanguageClient.java, src/main/java/com/redhat/devtools/lsp4ij/client/ProjectIndexingListener.java, src/main/java/com/redhat/devtools/lsp4ij/client/ProjectIndexingManager.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/intention/LSPIntentionAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewFactory.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewModel.java, src/main/java/com/redhat/devtools/lsp4ij/features/foldingRange/LSPFoldingRangeBuilder.java, src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightUsagesHandlerFactory.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokensHighlightVisitor.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/CodeVisionEditorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeatureManager.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/CodeLensCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/FoldingRangeCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/InlayHintCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/TextDocumentServerCapabilityRegistry.java, src/main/resources/META-INF/plugin.xml
perf: wait for project indexing finished
See discussion at https://github.com/redhat-developer/lsp4ij/discussions/571
=> perf: wait for project indexing finished

src/main/java/com/redhat/devtools/lsp4ij/usages/LSPFindUsagesHandlerFactory.java
=> fix: enable find usages.

src/main/java/com/redhat/devtools/lsp4ij/features/typeHierarchy/LSPTypeHierarchyProvider.java
fix : NPE when type hierarchy is shown
=> fix : NPE when type hierarchy is shown

src/main/java/com/redhat/devtools/lsp4ij/ConnectDocumentToLanguageServerSetupParticipant.java, src/main/java/com/redhat/devtools/lsp4ij/client/IndexAwareLanguageClient.java, src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingAppLifecycleListener.java, src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingDumbAndScanningStrategy.java, src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingManager.java, src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingOnlyDumbStrategy.java, src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingStrategyBase.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPGoToAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/intention/LSPIntentionAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/completion/LSPCompletionContributor.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkAnnotator.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewFactory.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPDocumentSymbolStructureViewModel.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentation/LSPDocumentationTargetProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/foldingRange/LSPFoldingRangeBuilder.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/AbstractLSPFormattingService.java, src/main/java/com/redhat/devtools/lsp4ij/features/hierarchy/LSPHierarchyProviderBase.java, src/main/java/com/redhat/devtools/lsp4ij/features/highlight/LSPHighlightUsagesHandlerFactory.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokensHighlightVisitor.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPFindUsagesHandlerFactory.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageTargetProvider.java, src/main/resources/META-INF/plugin.xml
fix: remove using internal API ProjectIndexingActivityHistoryListener
=> fix: remove using internal API ProjectIndexingActivityHistoryListener

docs/user-defined-ls/sourcekit-lsp.md, src/main/resources/templates/sourcekit-lsp/README.md
fix: minor fix for SourceToolkit-LSP doc
=> fix: minor fix for SourceToolkit-LSP doc

src/main/resources/META-INF/plugin.xml
=> chore: changelog for 0.8.1

src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedCompletionFeature.java, src/main/resources/messages/LanguageServerBundle.properties
fix: minor fix for client configuration
=> fix: minor fix for client configuration

src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedCompletionFeature.java
Totally your call as to whether you want to merge this or discard it, but this was the last of the feedback I'd received.
=> fix: One more commit for issue 626 that removes an unnecessary instanceof/cast.

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/launching/UserDefinedLanguageServerSettings.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplate.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManager.java, src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerView.java, src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/AbstractLSPJsonSchemaFileProvider.java, src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/AbstractLSPJsonSchemaFileSystemProvider.java, src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/LSPClientConfigurationJsonSchemaFileProvider.java, src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/LSPJsonSchemaLightVirtualFile.java, src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/LSPJsonSchemaProviderFactory.java, src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/LSPServerConfigurationJsonSchemaFileProvider.java, src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/LSPServerConfigurationJsonSchemaManager.java, src/main/java/com/redhat/devtools/lsp4ij/settings/ui/EditJsonSchemaDialog.java, src/main/java/com/redhat/devtools/lsp4ij/settings/ui/JsonTextField.java, src/main/java/com/redhat/devtools/lsp4ij/settings/ui/LanguageServerPanel.java, src/main/java/com/redhat/devtools/lsp4ij/settings/ui/SchemaBackedJsonTextField.java, src/main/resources/META-INF/plugin-json.xml, src/main/resources/messages/LanguageServerBundle.properties, src/main/resources/templates/typescript-language-server/settings.schema.json, src/main/resources/templates/vscode-css-language-server/settings.schema.json, src/test/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerDefinitionSerializerTest.java, src/test/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManagerTest.java
feat: associate JSON Schema for language server configuration
This PR provides JSON Schema for TypeScript and CSS. Here a demo with TypeScript config:
@SCWells72 you will need to recreate the TypeScript config to load the JSON Schema.
The JSON Schema uses LightVirtualFile (in memory) but I had to create MyLightVirtualFile otherwise JSONService doesn't evict the cache.
The idea is to create 100 JsonSchemaProvider which are used for each configuration editor. When a dialog is closed andthe editor is disposed  JsonSchemaProvider is marked as unused and can be used by other editor configuration.
If a Configuration editor is mapped to a JSON Schema, the hyperlink display `Edit Json Schema`:
This hyperlink open a dialog which is filled with the JSON Schema that you can update it.
If there are …
=> feat: associate JSON Schema for language server configuration

src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/AbstractLSPJsonSchemaFileProvider.java, src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/AbstractLSPJsonSchemaFileSystemProvider.java, src/main/java/com/redhat/devtools/lsp4ij/settings/jsonSchema/LSPServerConfigurationJsonSchemaFileProvider.java
fix: remove use of internal API
=> fix: remove use of internal API

gradle.properties
=> chore: bump to 0.9.0

src/main/java/com/redhat/devtools/lsp4ij/settings/ui/LanguageServerPanel.java
fix: Null Pointer Exception occurs when opening a project
Fixes #696
=> fix: Null Pointer Exception occurs when opening a project

src/main/resources/META-INF/plugin.xml
=> chore: changelog for 0.9.0

src/main/java/com/redhat/devtools/lsp4ij/usages/LSPExternalReferencesFinder.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSearcher.java
This is a fresh version of #711. See that PR for conversation history.
=> fix: Addressed issues with LSP Find Usages implementation (issue 708)

docs/UserDefinedLanguageServer.md, docs/user-defined-ls/vue-js-language-server.md
=> docs: Add Vue JS docs

src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPExtendWordSelectionHandler.java
fix: Cannot select word at given offset
Fixes #731
=> fix: Cannot select word at given offset

docs/dap/user-defined-dap/vscode-js-debug.md
docs: add configuration screenshot
=> docs: add configuration screenshot

docs/dap/DAP.md
=> docs: fix delve url

src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterDescriptor.java, src/main/java/com/redhat/devtools/lsp4ij/internal/IntelliJPlatformUtils.java
feat: set clientName on initialize of DAP server
=> feat: set clientName on initialize of DAP server

docs/LSPApi.md, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPOnTypeFormattingFeature.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPProgressFeature.java, src/main/java/com/redhat/devtools/lsp4ij/features/progress/LSPProgressManager.java
fix: Support customize progress notifications UI
Fixes #772
=> fix: Support customize progress notifications UI

src/main/java/com/redhat/devtools/lsp4ij/commands/CommandExecutor.java
fix: NPE in CommandExecutor
See https://github.com/clojure-lsp/clojure-lsp-intellij/issues/53#issuecomment-2620084924
=> fix: NPE in CommandExecutor

src/main/java/com/redhat/devtools/lsp4ij/dap/DAPServerReadyTracker.java, src/main/java/com/redhat/devtools/lsp4ij/dap/configurations/DAPRunConfiguration.java, src/main/java/com/redhat/devtools/lsp4ij/dap/configurations/DAPRunConfigurationOptions.java, src/main/java/com/redhat/devtools/lsp4ij/dap/configurations/DAPSettingsEditor.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterDescriptor.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterManager.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/ServerReadyConfig.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/templates/DAPTemplate.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/templates/DAPTemplateDeserializer.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/userdefined/UserDefinedDebugAdapterDescriptorFactory.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/UserDefinedDebugAdapterDescriptorFactorySettings.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/DAPConnectingServerConfigurationPanel.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/DebugAdapterDescriptorFactoryPanel.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/DebugAdapterDescriptorFactoryView.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/NewDebugAdapterDescriptorFactoryDialog.java
feat: use int instead of String for DAP connect timeout
=> feat: use int instead of String for DAP connect timeout

src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPClientSideOnTypeFormattingTypedHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPServerSideOnTypeFormattingHelper.java
fix: avoid freezing LSP typed handler
=> fix: avoid freezing LSP typed handler

src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/LSPLazyCodeActionIntentionAction.java
Exception LSPLazyCodeActionIntentionAction.getText must not return null
Fixes #713
I don't know how to reproduce but this PR fixes the issue #713
=> Exception LSPLazyCodeActionIntentionAction.getText must not return null

src/main/java/com/redhat/devtools/lsp4ij/LSPIJTextMateUtils.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/variables/providers/TextMateVariableRangeRegistrar.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeBlockProvider/LSPCodeBlockUtils.java, src/main/java/com/redhat/devtools/lsp4ij/internal/SimpleLanguageUtils.java
fix: java.lang.NoClassDefFoundError: TextMateFile
Fixes #815
=> fix: java.lang.NoClassDefFoundError: TextMateFile

src/main/java/com/redhat/devtools/lsp4ij/LSPIJUtils.java, src/test/java/com/redhat/devtools/lsp4ij/LSPIJUtils_applyWorkspaceEdit_ZigTest.java
Resolves https://github.com/redhat-developer/lsp4ij/issues/817
=> fix: Made code action edit apply logic order-independent

src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPFormattingSupport.java
fix: ignore cancel exception while formatting
=> fix: ignore cancel exception while formatting

src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/DocumentSymbolData.java
=> fix: null range on DocumentSymbolData

docs/dap/UserGuide.md
docs: add Python Debugpy in the DAP server list
=> docs: add Python Debugpy in the DAP server list

src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPDeclarativeInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeatureManager.java
fix: LSP inlay hint request blocks the EDT
Fixes #835
=> fix: LSP inlay hint request blocks the EDT

src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugProcess.java, src/main/java/com/redhat/devtools/lsp4ij/dap/DAPServerReadyTracker.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterDescriptorFactory.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DefaultDebugAdapterDescriptor.java
fix: Unable to connect to non-localhost DAP server
Fixes #863
=> fix: Unable to connect to non-localhost DAP server

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore: bump to 0.11.0

README.md
https://github.com/pawrequest/redscript-intellij
=> docs: add redscript intelliJ

src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugProcess.java, src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugRunner.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/variables/providers/DefaultVariableRangeRegistrar.java, src/main/resources/dap/templates/python-debugpy/template.json
fix: don't use internal API
This PR fixes the 2 internal problems:
=> fix: don't use internal API

src/main/java/com/redhat/devtools/lsp4ij/LSPRequestConstants.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPSemanticTokensFeature.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/LSPSemanticTokensSupport.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/SemanticTokensCapabilityRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/TextDocumentServerCapabilityRegistry.java
fix: support for register semanticTokens capability with dynamic mode
=> fix: support for register semanticTokens capability with dynamic mode

gradle.properties
=> chore: Bump to 0.12.0

src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java, src/main/java/com/redhat/devtools/lsp4ij/LSPFileListener.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java
fix: Freeze when language server is started from the EDT
Fixes #878
=> fix: Freeze when language server is started from the EDT

src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java
chore: add comments for read action before didOpen
=> chore: add comments for read action before didOpen

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
perf: improve perf of language server is stopping when project is closed.
=> perf: improve perf of language server is stopping when project is closed.

README.md
Hello @angelozerr,
Based on your recommendation in https://github.com/robotcodedev/robotcode/issues/406, I've updated the README.md to include RobotCode. I hope this meets your expectations.
Thanks!
=> docs: add RobotCode to README.md

src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/CodeLensData.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/CodeLensDataResult.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensEditorFactoryListener.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/UnresolvedCodeLensViewportContext.java, src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java, src/main/java/com/redhat/devtools/lsp4ij/internal/PsiFileChangedException.java
=> fix: fix flaky codelens

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
fix: Error while getting 'textDocument/inlayHint' capability java.util.ConcurrentModificationException
Fixes #914
=> fix: Error while getting 'textDocument/inlayHint' capability java.util.ConcurrentModificationException

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinitionListener.java, src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerView.java, src/main/java/com/redhat/devtools/lsp4ij/settings/UserDefinedLanguageServerSettings.java
fix: fix mapping, client config, debug suspend changes
=> fix: fix mapping, client config, debug suspend changes

.gitignore, README.md
I've created a plugin that uses lsp4ij :) 
cc @angelozerr
=> docs: add a project using lsp4ij

src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/viewProvider/LSPSemanticTokensFileViewProviderHelper.java
fix: remove isInexAll to avoid freeze.
=> fix: remove isInexAll to avoid freeze.

src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkGotoDeclarationHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkPsiElement.java
fix: java.lang.IllegalStateException: Calling invokeAndWait from read-action leads to possible deadlock.
Fixes #593
=> fix: java.lang.IllegalStateException: Calling invokeAndWait from read-action leads to possible deadlock.

src/main/java/com/redhat/devtools/lsp4ij/features/documentLink/LSPDocumentLinkPsiElement.java
fix: create a fake psi file for document link
=> fix: create a fake psi file for document link

src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsageSearcher.java
perf: disable call of processExternalReferences
=> perf: disable call of processExternalReferences

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/EditorBehaviorFeature.java, src/main/java/com/redhat/devtools/lsp4ij/launching/FileTypeSettings.java, src/test/java/com/redhat/devtools/lsp4ij/features/formatting/TypeScriptEditorImprovementsTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPBreadcrumbsProviderFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPClientSideOnTypeFormattingFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPCompletionClientConfigFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPSemanticTokensFileViewProviderFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPServerSideOnTypeFormattingFixtureTestCase.java
This is a fresh branch/PR for #906 to facilitate a rebase-based squash merge.
=> fix: Prospective fix for the freeze encountered by one person helping test the file view provider stuff

src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java
fix: ensure ReadAction when pull diagnostics must be refreshed
See https://github.com/redhat-developer/lsp4ij/discussions/899#discussioncomment-12675027
=> fix: ensure ReadAction when pull diagnostics must be refreshed

docs/UserDefinedLanguageServer.md
docs: add Docker Language Server link
//cc @rcjsuen
=> docs: add Docker Language Server link

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
fix: ensure that PsiFile.getVirualFile() is not null
=> fix: ensure that PsiFile.getVirualFile() is not null

src/test/java/com/redhat/devtools/lsp4ij/features/diagnostics/TypeScriptDiagnosticsTest.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/LSPDiagnosticsFixtureTestCase.java, src/test/java/com/redhat/devtools/lsp4ij/fixtures/impl/LSPCodeInsightTestFixtureImpl.java
test: tests for LSP diagnostics
=> test: tests for LSP diagnostics

src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPSelectionRangeSupport.java
fix: Cannot select word at given offset error
Fixes #957
=> fix: Cannot select word at given offset error

src/main/java/com/redhat/devtools/lsp4ij/features/completion/snippet/LspSnippetParser.java, src/test/java/com/redhat/devtools/lsp4ij/features/completion/snippet/EscapeTest.java
fix: improve snippet escape (with tests from Huly Code)
See #959
=> fix: improve snippet escape (from Huly Code)

src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowFactory.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/inspector/ActivateSemanticTokensInspectorToolWindowAction.java, src/main/java/com/redhat/devtools/lsp4ij/features/semanticTokens/inspector/SemanticTokensInspectorToolWindowFactory.java, src/main/java/com/redhat/devtools/lsp4ij/ui/LSPToolWindowId.java, src/main/resources/META-INF/plugin.xml
feat: Hide Semantic Tokens Inspector from toolbar
Fixes #461
=> feat: Hide Semantic Tokens Inspector from toolbar

gradle.properties
=> chore: bump to 0.13.0

src/main/java/com/redhat/devtools/lsp4ij/features/codeBlockProvider/LSPCodeBlockProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/foldingRange/LSPFoldingRangeBuilder.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPClientSideOnTypeFormattingTypedHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPExtendWordSelectionHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPSelectionRangeSupport.java
perf: permanent deadlock at "selecting word at given offset"
Fixes #955
=> perf: permanent deadlock at "selecting word at given offset"

src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPClient.java
fix: dont terminate the debuggee when debug session in attach mode is terminated.
=> fix: dont terminate the debuggee when debug session in attach mode is terminated.

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/ServerMessageHandler.java, src/main/java/com/redhat/devtools/lsp4ij/client/indexing/ProjectIndexingManager.java, src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugProcess.java, src/main/java/com/redhat/devtools/lsp4ij/dap/DAPServerReadyTracker.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPClient.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPFeatureSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeAction/quickfix/LSPLazyCodeActions.java, src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/LSPCodeLensProvider.java, src/main/java/com/redhat/devtools/lsp4ij/installation/ServerInstallerBase.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CompletableFutures.java, src/main/java/com/redhat/devtools/lsp4ij/internal/PromiseToCompletableFuture.java
fix: don't throw any exception when future is cancelled
Fixes #978
=> fix: don't throw any exception when future is cancelled

src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java, src/main/java/com/redhat/devtools/lsp4ij/usages/LSPUsagesManager.java
fix: check that future is not done to cancel it
=> fix: check that future is not done to cancel it

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorerLifecycleListener.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPBreadcrumbsRefreshListener.java, src/main/java/com/redhat/devtools/lsp4ij/internal/LSPPostStartupActivity.java, src/main/java/com/redhat/devtools/lsp4ij/lifecycle/LanguageServerLifecycleListener.java
perf: debounce LSP console tracing
=> perf: debounce LSP console tracing

build.gradle.kts, gradle.properties
build: Align LSP4J with JetBrains LSP-API + exclude gson
=> build: Align LSP4J with JetBrains LSP-API + exclude gson

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/console/LSPConsoleToolWindowFactory.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorerLifecycleListener.java, src/main/java/com/redhat/devtools/lsp4ij/internal/LSPPostStartupActivity.java
fix: force load of language server settings in the lsp console factory
=> fix: force load of language server settings in the lsp console factory

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/features/documentSymbol/LSPBreadcrumbsRefreshListener.java
Refresh breadcrumn on load when symbol ready
=> Refresh breadcrumn on load when symbol ready

src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPDeclarativeInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPDocumentRefreshableFeatureSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/AbstractLSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/color/LSPColorSupport.java, src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/features/inlayhint/LSPInlayHintsSupport.java, src/main/java/com/redhat/devtools/lsp4ij/internal/editor/EditorFeatureManager.java
fix: cancel refresh editor future
=> fix: cancel refresh editor future

src/main/java/com/redhat/devtools/lsp4ij/LSPFileSupport.java
fix: don't create PsiFile Alarm when support is disposed.
=> fix: don't create PsiFile Alarm when support is disposed.

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
fix: ensure process is stopped before starting a new process
=> fix: ensure process is stopped before starting a new process

src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPExtendWordSelectionHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/selectionRange/LSPWordSelectionFilter.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/lsp4ij/features/selectionRange/ClojureSelectionRangeTest.java
fix: expand selection feature not respecting server `textDocument/selectionRange` response
Fixes #1007
=> fix: expand selection feature not respecting server `textDocument/selectionRange` response

src/main/resources/META-INF/plugin.xml
=> chore: changelog for 0.13.0

src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPClient.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterDescriptor.java
fix: Debugpy: an exception is not causing the debugger to break execution
Fixes #1008
=> fix: Debugpy: an exception is not causing the debugger to break execution

src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPClient.java
=> fix: improve dap exception

src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebuggerEditorsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPBreakpointHandler.java, src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPBreakpointType.java, src/main/java/com/redhat/devtools/lsp4ij/dap/evaluation/DAPExpressionCodeFragment.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPClientSideOnTypeFormattingTypedHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/formatting/LSPServerSideOnTypeFormattingHelper.java
feat: support for condition DAP breakpoint
=> feat: support for condition DAP breakpoint

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/resources/META-INF/plugin.xml
fix: activate LSP semantic PsiFile for TEXT language
See #1018
=> fix: activate LSP semantic PsiFile for TEXT language

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java
fix: Collect language from fileNamePatterns to enable inlayhint and find usages
Fixes #1023
=> fix: Collect language from fileNamePatterns to enable inlayhint and find usages

src/main/java/com/redhat/devtools/lsp4ij/dap/DAPIJUtils.java, src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/DAPBreakpointHandler.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPStackFrame.java
fix: take care of invalid DAP source path
=> fix: take care of invalid DAP source path

src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticUtils.java
fix: Read access is allowed from inside read-action when reporting problem
Fixes #1032
=> fix: Read access is allowed from inside read-action when reporting problem

src/main/java/com/redhat/devtools/lsp4ij/OpenedDocument.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticAnnotator.java
fix: refresh diagnostics on first time
=> fix: refresh diagnostics on first time

src/main/java/com/redhat/devtools/lsp4ij/client/features/FileUriSupport.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/FileUriSupportBase.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedClientFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedFileUriSupport.java
feat: simplify file uri support.
=> feat: simplify file uri support.

src/main/java/com/redhat/devtools/lsp4ij/server/capabilities/OnTypeFormattingCapabilityRegistry.java
fix: OnTypeFormattingCapabilityRegistry errors out
Fixes #1036
=> fix: OnTypeFormattingCapabilityRegistry errors out

src/main/resources/messages/DAPBundle_zh_CN.properties, src/main/resources/messages/LanguageServerBundle_zh_CN.properties
feat: Add Chinese language support
Added Simplified Chinese language support for the LSP4IJ plugin, including:
- Added DAPBundle_zh_CN.properties file with Chinese translations for Debug Adapter Protocol related content
- Added LanguageServerBundle_zh_CN.properties file with Chinese translations for Language Server related content
=> feat: Add Chinese localization for Language Server and DAP properties

src/main/java/com/redhat/devtools/lsp4ij/features/workspaceSymbol/AbstractLSPWorkspaceSymbolContributor.java
fix: LSP4IJ plugin causes IDEA to freeze when workspace symbol is requested
Fixes #1048
=> fix: LSP4IJ plugin causes IDEA to freeze when workspace symbol is requested

src/main/resources/templates/lsp/erlang-ls/installer.json
feat: add erlang-ls installer.json
=> feat: add erlang-ls installer.json

docs/UserDefinedLanguageServerTemplate.md, src/main/resources/templates/lsp/erlang-ls/installer.json
docs: How to contribute to User-defined language server template
=> docs: How to contribute to User-defined language server template

src/main/java/com/redhat/devtools/lsp4ij/JSONUtils.java, src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java
fix: get JSON executable correctly.
=> fix: get JSON executable correctly.

src/main/java/com/redhat/devtools/lsp4ij/installation/definition/tasks/DownloadTask.java, src/main/resources/templates/lsp/rust-analyzer/installer.json
fix: fix arch of rust unix installer
=> fix: fix arch of rust unix installer

src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/templates/DAPTemplateManager.java, src/main/java/com/redhat/devtools/lsp4ij/installation/definition/tasks/DownloadTask.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManager.java, src/main/resources/templates/lsp/erlang-ls/installer.json
=> feat: sort template by name

src/main/java/com/redhat/devtools/lsp4ij/installation/DeclarativeLanguageServerInstaller.java, src/main/java/com/redhat/devtools/lsp4ij/installation/ServerInstallerBase.java, src/main/resources/templates/lsp/jdtls/installer.json
=> fix: check installation bug

src/test/java/com/redhat/devtools/lsp4ij/features/files/FileSystemWatcherManagerTest.java
It's a minor, test-only change, just something that was bugging me.
=> test: address FileSystemWatcherManagerTest lint warnings

gradle.properties
chore: Bump to 0.14.0-SNAPSHOT
=> chore: Bump to 0.14.0-SNAPSHOT

src/main/resources/templates/lsp/dockerfile-language-server/installer.json
feat: add installer.json for dockerfile-language-server
=> feat: add installer.json for dockerfile-language-server

src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/launching/UserDefinedLanguageServerSettings.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplate.java, src/main/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManager.java, src/main/java/com/redhat/devtools/lsp4ij/launching/ui/NewLanguageServerDialog.java, src/main/java/com/redhat/devtools/lsp4ij/launching/ui/UICommandLineUpdater.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinitionListener.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageClient.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageListener.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedStreamConnectionProvider.java, src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerView.java, src/main/java/com/redhat/devtools/lsp4ij/settings/ui/LanguageServerPanel.java, src/main/resources/messages/LanguageServerBundle.properties, src/main/resources/templates/lsp/rust-analyzer/experimental.json, src/main/resources/templates/lsp/rust-analyzer/settings.json, src/test/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerDefinitionSerializerTest.java, src/test/java/com/redhat/devtools/lsp4ij/launching/templates/LanguageServerTemplateManagerTest.java
feat: add Experimental JSON editor
Fixes #503
=> feat: add Experimental JSON editor

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerFactory.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/client/features/LSPClientFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorerLifecycleListener.java, src/main/java/com/redhat/devtools/lsp4ij/installation/DeclarativeLanguageServerInstaller.java, src/main/java/com/redhat/devtools/lsp4ij/installation/LanguageServerInstallerBase.java, src/main/java/com/redhat/devtools/lsp4ij/installation/ServerInstaller.java, src/main/java/com/redhat/devtools/lsp4ij/installation/ServerInstallerBase.java, src/main/java/com/redhat/devtools/lsp4ij/installation/definition/InstallerContext.java, src/main/java/com/redhat/devtools/lsp4ij/installation/definition/tasks/DownloadTask.java, src/main/java/com/redhat/devtools/lsp4ij/installation/definition/tasks/ExecTask.java, src/main/java/com/redhat/devtools/lsp4ij/launching/ui/UICommandLineUpdater.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/extension/ExtensionLanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/CommandUtils.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedClientFeatures.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerDefinition.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/launching/UserDefinedLanguageServerInstaller.java, src/main/java/com/redhat/devtools/lsp4ij/settings/LanguageServerView.java
fix: stop all servers when Installation is executed from hyperlink
=> fix: stop all servers when Installation is executed from hyperlink

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
=> fix: show LSP logs again

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerManager.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServersRegistry.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServiceAccessor.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerProcessTreeNode.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerTreeRenderer.java, src/main/java/com/redhat/devtools/lsp4ij/installation/LanguageServerInstallerBase.java, src/main/java/com/redhat/devtools/lsp4ij/installation/ServerInstallerBase.java, src/main/java/com/redhat/devtools/lsp4ij/launching/ui/UICommandLineUpdater.java, src/main/java/com/redhat/devtools/lsp4ij/server/definition/LanguageServerDefinitionListener.java
fix: ensure starting server when installation is terminated
=> fix: ensure starting server when installation is terminated

src/main/resources/templates/lsp/metals/installer.json, src/main/resources/templates/lsp/sourcekit-lsp/installer.json
feat: add sourcekit lsp installer
=> feat: add sourcekit lsp installer

src/main/resources/templates/lsp/gopls/installer.json
=> feat: improve gopls installer

src/main/resources/templates/lsp/camel-lsp-server/settings.json, src/main/resources/templates/lsp/camel-lsp-server/settings.schema.json
fix: remove unused camel JSON properties
=> fix: remove unused camel JSON properties

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/console/explorer/LanguageServerExplorer.java
fix: wait for stop termination before launching install
=> fix: wait for stop termination before launching install

src/main/resources/META-INF/plugin.xml
chore: add changelog for 0.14.0
=> chore: add changelog for 0.14.0

docs/user-defined-ls/astro-ls.md
=> docs: Add Astro documentation

src/main/resources/templates/lsp/astro-ls/installer.json, src/main/resources/templates/lsp/svelte-language-server/installer.json, src/main/resources/templates/lsp/typescript-language-server/installer.json
fix: set working dir to node_modules dir.
=> fix: set working dir to node_modules dir.

src/main/java/com/redhat/devtools/lsp4ij/ui/LanguageServerSuggestionEditorNotificationProvider.java
feat: refresh editor notification for all opened files.
=> feat: refresh editor notification for all opened files.

src/main/resources/templates/lsp/vscode-css-language-server/template.json
feat: use the same start ls command for template/installer for CSS LS
=> feat: use the same start ls command for template/installer for CSS LS

src/main/resources/META-INF/plugin.xml
=> chore: changelog 0.14.1

src/main/resources/META-INF/plugin.xml
=> chore: changelog for 0.14.2

src/main/java/com/redhat/devtools/lsp4ij/dap/evaluation/DAPDebuggerEvaluator.java
fix: Support `repl evaluate` request for DAP in `Evaluate Window`
/cc @rcjsuen
=> fix: Support `repl evaluate` request for DAP in `Evaluate Window`

src/main/java/com/redhat/devtools/lsp4ij/dap/configurations/DAPRunConfiguration.java, src/main/java/com/redhat/devtools/lsp4ij/dap/configurations/DAPRunConfigurationOptions.java, src/main/java/com/redhat/devtools/lsp4ij/dap/configurations/DAPSettingsEditor.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/DebugAdapterServerPanel.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/DebugAdapterServerView.java, src/main/java/com/redhat/devtools/lsp4ij/dap/settings/ui/NewDebugAdapterServerDialog.java
fix: DAP environment variables do not appear to persist
Fixes #1114
=> fix: DAP environment variables do not appear to persist

src/main/java/com/redhat/devtools/lsp4ij/dap/completion/DAPLookupElementDecorator.java
=> fix: DAP completion apply fix

src/main/java/com/redhat/devtools/lsp4ij/dap/runInTerminal/external/ExternalTerminalService.java, src/main/java/com/redhat/devtools/lsp4ij/dap/runInTerminal/external/LinuxExternalTerminalService.java, src/main/java/com/redhat/devtools/lsp4ij/internal/ResponseErrorExceptionWrapper.java
feat: show external runInTerminal error
=> feat: show external runInTerminal error

src/main/java/com/redhat/devtools/lsp4ij/DocumentContentSynchronizer.java, src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java
fix: nil crashes on textDocument/didSave notification
Fixes #1202
=> fix: nil crashes on textDocument/didSave notification

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticUtils.java
fix: Failed to stop language server blocLanguageServer
Fixes #1206
=> fix: Failed to stop language server blocLanguageServer

src/main/java/com/redhat/devtools/lsp4ij/dap/evaluation/DAPDebuggerEvaluator.java
feat: show DAP variable value in hover
Here a sample with VSCode JS Debug:
//cc @rcjsuen please try it.
=> feat: show DAP variable value in hover

src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugProcess.java, src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebuggerEditorsProvider.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterDescriptor.java
feat: DAP API to customize debugger editors provider
=> feat: DAP API to customize debugger editors provider

src/main/resources/META-INF/plugin.xml
=> docs: add 1.15.0 changelog

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticUtils.java
fix: Too many non-blocking read actions submitted at once
See #1214
=> fix: Too many non-blocking read actions submitted at once

src/main/java/com/redhat/devtools/lsp4ij/dap/DAPDebugProcess.java, src/main/java/com/redhat/devtools/lsp4ij/dap/definitions/userdefined/UserDefinedDebugAdapterDescriptor.java, src/main/java/com/redhat/devtools/lsp4ij/dap/definitions/userdefined/UserDefinedDebugAdapterDescriptorFactory.java, src/main/java/com/redhat/devtools/lsp4ij/dap/descriptors/DebugAdapterDescriptor.java
feat: Show "Installer" tab only for user defined DAP server
=> feat: Show "Installer" tab only for user defined DAP server

gradle.properties, src/main/resources/META-INF/plugin.xml
=> build: changelog 0.16.0

docs/dap/DAPSupport.md, src/main/java/com/redhat/devtools/lsp4ij/dap/breakpoints/BreakpointHandlerBase.java, src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPClient.java, src/main/java/com/redhat/devtools/lsp4ij/dap/evaluation/DAPDebuggerEvaluator.java
feat: use supportsEvaluateForHovers capability to evaluate variable on hovers
=> feat: use supportsEvaluateForHovers capability to evaluate variable on hovers

src/main/java/com/redhat/devtools/lsp4ij/features/workspaceSymbol/AbstractLSPWorkspaceSymbolContributor.java, src/main/java/com/redhat/devtools/lsp4ij/internal/CancellationSupport.java
fix: Hit CancellationException when using "Shift+Shift" (Search Everywhere)
Fixes #1268
=> fix: Hit CancellationException when using "Shift+Shift" (Search Everywhere)

src/main/resources/META-INF/plugin.xml
=> docs: changelog for 0.16.1

src/main/java/com/redhat/devtools/lsp4ij/dap/runInTerminal/integrated/RunInIntegratedTerminalService.java
fix: NPE with RunInIntegratedTerminal when title is null
Fixes #1282
=> fix: NPE with RunInIntegratedTerminal when title is null

src/main/java/com/redhat/devtools/lsp4ij/features/codeLens/CodeLensData.java
fix: catch "content changed" error on codelens resolve
=> fix: catch "content changed" error on codelens resolve

src/main/java/com/redhat/devtools/lsp4ij/dap/client/DAPStackFrame.java
When DAP server (ex: Debugpy) returns stack frame with source which is null, but source path is filled:
```
[Trace - 19:55:54] Received response 'stackTrace - (9)' in 7ms.
Result: {
"stackFrames": [
{
"id": 2,
"name": "main",
"source": {
"path": "C:\\Users\\AngeloZerr\\test-projects\\hello-rust\\test.py",
"sourceReference": 0
},
"line": 3,
"column": 1
},
{
"id": 3,
"name": "\u003cmodule\u003e",
"source": {
"path": "C:\\Users\\AngeloZerr\\test-projects\\hello-rust\\test.py",
"sourceReference": 0
},
"line": 6,
"column": 1
}
],
"totalFrames": 2
}
```
It shows invalid frame:
This PR fixes that to use the path name from source.path.
//cc @@scweber-cisco
=> fix: use DAP source.path to avoid invalid_frame

src/main/java/com/redhat/devtools/lsp4ij/LanguageServerWrapper.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticHandler.java, src/main/java/com/redhat/devtools/lsp4ij/features/diagnostics/LSPDiagnosticsForServer.java
fix: Quick fix are not available after a restart
See https://github.com/redhat-developer/lsp4ij/discussions/1305#discussioncomment-14585360
=> fix: Quick fix are not available after a restart
